const pokemonName = [
  null,
  "Bulbasaur",
  "Ivysaur",
  "Venusaur",
  "Charmander",
  "Charmeleon",
  "Charizard",
  "Squirtle",
  "Wartortle",
  "Blastoise",
  "Caterpie",
  "Metapod",
  "Butterfree",
  "Weedle",
  "Kakuna",
  "Beedrill",
  "Pidgey",
  "Pidgeotto",
  "Pidgeot",
  "Rattata",
  "Raticate",
  "Spearow",
  "Fearow",
  "Ekans",
  "Arbok",
  "Pikachu",
  "Raichu",
  "Sandshrew",
  "Sandslash",
  "Nidoran♀",
  "Nidorina",
  "Nidoqueen",
  "Nidoran♂",
  "Nidorino",
  "Nidoking",
  "Clefairy",
  "Clefable",
  "Vulpix",
  "Ninetales",
  "Jigglypuff",
  "Wigglytuff",
  "Zubat",
  "Golbat",
  "Oddish",
  "Gloom",
  "Vileplume",
  "Paras",
  "Parasect",
  "Venonat",
  "Venomoth",
  "Diglett",
  "Dugtrio",
  "Meowth",
  "Persian",
  "Psyduck",
  "Golduck",
  "Mankey",
  "Primeape",
  "Growlithe",
  "Arcanine",
  "Poliwag",
  "Poliwhirl",
  "Poliwrath",
  "Abra",
  "Kadabra",
  "Alakazam",
  "Machop",
  "Machoke",
  "Machamp",
  "Bellsprout",
  "Weepinbell",
  "Victreebel",
  "Tentacool",
  "Tentacruel",
  "Geodude",
  "Graveler",
  "Golem",
  "Ponyta",
  "Rapidash",
  "Slowpoke",
  "Slowbro",
  "Magnemite",
  "Magneton",
  "Farfetch'd",
  "Doduo",
  "Dodrio",
  "Seel",
  "Dewgong",
  "Grimer",
  "Muk",
  "Shellder",
  "Cloyster",
  "Gastly",
  "Haunter",
  "Gengar",
  "Onix",
  "Drowzee",
  "Hypno",
  "Krabby",
  "Kingler",
  "Voltorb",
  "Electrode",
  "Exeggcute",
  "Exeggutor",
  "Cubone",
  "Marowak",
  "Hitmonlee",
  "Hitmonchan",
  "Lickitung",
  "Koffing",
  "Weezing",
  "Rhyhorn",
  "Rhydon",
  "Chansey",
  "Tangela",
  "Kangaskhan",
  "Horsea",
  "Seadra",
  "Goldeen",
  "Seaking",
  "Staryu",
  "Starmie",
  "Mr. Mime",
  "Scyther",
  "Jynx",
  "Electabuzz",
  "Magmar",
  "Pinsir",
  "Tauros",
  "Magikarp",
  "Gyarados",
  "Lapras",
  "Ditto",
  "Eevee",
  "Vaporeon",
  "Jolteon",
  "Flareon",
  "Porygon",
  "Omanyte",
  "Omastar",
  "Kabuto",
  "Kabutops",
  "Aerodactyl",
  "Snorlax",
  "Articuno",
  "Zapdos",
  "Moltres",
  "Dratini",
  "Dragonair",
  "Dragonite",
  "Mewtwo",
  "Mew",
  "Chikorita",
  "Bayleef",
  "Meganium",
  "Cyndaquil",
  "Quilava",
  "Typhlosion",
  "Totodile",
  "Croconaw",
  "Feraligatr",
  "Sentret",
  "Furret",
  "Hoothoot",
  "Noctowl",
  "Ledyba",
  "Ledian",
  "Spinarak",
  "Ariados",
  "Crobat",
  "Chinchou",
  "Lanturn",
  "Pichu",
  "Cleffa",
  "Igglybuff",
  "Togepi",
  "Togetic",
  "Natu",
  "Xatu",
  "Mareep",
  "Flaaffy",
  "Ampharos",
  "Bellossom",
  "Marill",
  "Azumarill",
  "Sudowoodo",
  "Politoed",
  "Hoppip",
  "Skiploom",
  "Jumpluff",
  "Aipom",
  "Sunkern",
  "Sunflora",
  "Yanma",
  "Wooper",
  "Quagsire",
  "Espeon",
  "Umbreon",
  "Murkrow",
  "Slowking",
  "Misdreavus",
  "Unown",
  "Wobbuffet",
  "Girafarig",
  "Pineco",
  "Forretress",
  "Dunsparce",
  "Gligar",
  "Steelix",
  "Snubbull",
  "Granbull",
  "Qwilfish",
  "Scizor",
  "Shuckle",
  "Heracross",
  "Sneasel",
  "Teddiursa",
  "Ursaring",
  "Slugma",
  "Magcargo",
  "Swinub",
  "Piloswine",
  "Corsola",
  "Remoraid",
  "Octillery",
  "Delibird",
  "Mantine",
  "Skarmory",
  "Houndour",
  "Houndoom",
  "Kingdra",
  "Phanpy",
  "Donphan",
  "Porygon2",
  "Stantler",
  "Smeargle",
  "Tyrogue",
  "Hitmontop",
  "Smoochum",
  "Elekid",
  "Magby",
  "Miltank",
  "Blissey",
  "Raikou",
  "Entei",
  "Suicune",
  "Larvitar",
  "Pupitar",
  "Tyranitar",
  "Lugia",
  "Ho-Oh",
  "Celebi",
  "Treecko",
  "Grovyle",
  "Sceptile",
  "Torchic",
  "Combusken",
  "Blaziken",
  "Mudkip",
  "Marshtomp",
  "Swampert",
  "Poochyena",
  "Mightyena",
  "Zigzagoon",
  "Linoone",
  "Wurmple",
  "Silcoon",
  "Beautifly",
  "Cascoon",
  "Dustox",
  "Lotad",
  "Lombre",
  "Ludicolo",
  "Seedot",
  "Nuzleaf",
  "Shiftry",
  "Taillow",
  "Swellow",
  "Wingull",
  "Pelipper",
  "Ralts",
  "Kirlia",
  "Gardevoir",
  "Surskit",
  "Masquerain",
  "Shroomish",
  "Breloom",
  "Slakoth",
  "Vigoroth",
  "Slaking",
  "Nincada",
  "Ninjask",
  "Shedinja",
  "Whismur",
  "Loudred",
  "Exploud",
  "Makuhita",
  "Hariyama",
  "Azurill",
  "Nosepass",
  "Skitty",
  "Delcatty",
  "Sableye",
  "Mawile",
  "Aron",
  "Lairon",
  "Aggron",
  "Meditite",
  "Medicham",
  "Electrike",
  "Manectric",
  "Plusle",
  "Minun",
  "Volbeat",
  "Illumise",
  "Roselia",
  "Gulpin",
  "Swalot",
  "Carvanha",
  "Sharpedo",
  "Wailmer",
  "Wailord",
  "Numel",
  "Camerupt",
  "Torkoal",
  "Spoink",
  "Grumpig",
  "Spinda",
  "Trapinch",
  "Vibrava",
  "Flygon",
  "Cacnea",
  "Cacturne",
  "Swablu",
  "Altaria",
  "Zangoose",
  "Seviper",
  "Lunatone",
  "Solrock",
  "Barboach",
  "Whiscash",
  "Corphish",
  "Crawdaunt",
  "Baltoy",
  "Claydol",
  "Lileep",
  "Cradily",
  "Anorith",
  "Armaldo",
  "Feebas",
  "Milotic",
  "Castform",
  "Kecleon",
  "Shuppet",
  "Banette",
  "Duskull",
  "Dusclops",
  "Tropius",
  "Chimecho",
  "Absol",
  "Wynaut",
  "Snorunt",
  "Glalie",
  "Spheal",
  "Sealeo",
  "Walrein",
  "Clamperl",
  "Huntail",
  "Gorebyss",
  "Relicanth",
  "Luvdisc",
  "Bagon",
  "Shelgon",
  "Salamence",
  "Beldum",
  "Metang",
  "Metagross",
  "Regirock",
  "Regice",
  "Registeel",
  "Latias",
  "Latios",
  "Kyogre",
  "Groudon",
  "Rayquaza",
  "Jirachi",
  "Deoxys",
  "Turtwig",
  "Grotle",
  "Torterra",
  "Chimchar",
  "Monferno",
  "Infernape",
  "Piplup",
  "Prinplup",
  "Empoleon",
  "Starly",
  "Staravia",
  "Staraptor",
  "Bidoof",
  "Bibarel",
  "Kricketot",
  "Kricketune",
  "Shinx",
  "Luxio",
  "Luxray",
  "Budew",
  "Roserade",
  "Cranidos",
  "Rampardos",
  "Shieldon",
  "Bastiodon",
  "Burmy",
  "Wormadam",
  "Mothim",
  "Combee",
  "Vespiquen",
  "Pachirisu",
  "Buizel",
  "Floatzel",
  "Cherubi",
  "Cherrim",
  "Shellos",
  "Gastrodon",
  "Ambipom",
  "Drifloon",
  "Drifblim",
  "Buneary",
  "Lopunny",
  "Mismagius",
  "Honchkrow",
  "Glameow",
  "Purugly",
  "Chingling",
  "Stunky",
  "Skuntank",
  "Bronzor",
  "Bronzong",
  "Bonsly",
  "Mime Jr.",
  "Happiny",
  "Chatot",
  "Spiritomb",
  "Gible",
  "Gabite",
  "Garchomp",
  "Munchlax",
  "Riolu",
  "Lucario",
  "Hippopotas",
  "Hippowdon",
  "Skorupi",
  "Drapion",
  "Croagunk",
  "Toxicroak",
  "Carnivine",
  "Finneon",
  "Lumineon",
  "Mantyke",
  "Snover",
  "Abomasnow",
  "Weavile",
  "Magnezone",
  "Lickilicky",
  "Rhyperior",
  "Tangrowth",
  "Electivire",
  "Magmortar",
  "Togekiss",
  "Yanmega",
  "Leafeon",
  "Glaceon",
  "Gliscor",
  "Mamoswine",
  "Porygon-Z",
  "Gallade",
  "Probopass",
  "Dusknoir",
  "Froslass",
  "Rotom",
  "Uxie",
  "Mesprit",
  "Azelf",
  "Dialga",
  "Palkia",
  "Heatran",
  "Regigigas",
  "Giratina",
  "Cresselia",
  "Phione",
  "Manaphy",
  "Darkrai",
  "Shaymin",
  "Arceus",
  "Victini",
  "Snivy",
  "Servine",
  "Serperior",
  "Tepig",
  "Pignite",
  "Emboar",
  "Oshawott",
  "Dewott",
  "Samurott",
  "Patrat",
  "Watchog",
  "Lillipup",
  "Herdier",
  "Stoutland",
  "Purrloin",
  "Liepard",
  "Pansage",
  "Simisage",
  "Pansear",
  "Simisear",
  "Panpour",
  "Simipour",
  "Munna",
  "Musharna",
  "Pidove",
  "Tranquill",
  "Unfezant",
  "Blitzle",
  "Zebstrika",
  "Roggenrola",
  "Boldore",
  "Gigalith",
  "Woobat",
  "Swoobat",
  "Drilbur",
  "Excadrill",
  "Audino",
  "Timburr",
  "Gurdurr",
  "Conkeldurr",
  "Tympole",
  "Palpitoad",
  "Seismitoad",
  "Throh",
  "Sawk",
  "Sewaddle",
  "Swadloon",
  "Leavanny",
  "Venipede",
  "Whirlipede",
  "Scolipede",
  "Cottonee",
  "Whimsicott",
  "Petilil",
  "Lilligant",
  "Basculin",
  "Sandile",
  "Krokorok",
  "Krookodile",
  "Darumaka",
  "Darmanitan",
  "Maractus",
  "Dwebble",
  "Crustle",
  "Scraggy",
  "Scrafty",
  "Sigilyph",
  "Yamask",
  "Cofagrigus",
  "Tirtouga",
  "Carracosta",
  "Archen",
  "Archeops",
  "Trubbish",
  "Garbodor",
  "Zorua",
  "Zoroark",
  "Minccino",
  "Cinccino",
  "Gothita",
  "Gothorita",
  "Gothitelle",
  "Solosis",
  "Duosion",
  "Reuniclus",
  "Ducklett",
  "Swanna",
  "Vanillite",
  "Vanillish",
  "Vanilluxe",
  "Deerling",
  "Sawsbuck",
  "Emolga",
  "Karrablast",
  "Escavalier",
  "Foongus",
  "Amoonguss",
  "Frillish",
  "Jellicent",
  "Alomomola",
  "Joltik",
  "Galvantula",
  "Ferroseed",
  "Ferrothorn",
  "Klink",
  "Klang",
  "Klinklang",
  "Tynamo",
  "Eelektrik",
  "Eelektross",
  "Elgyem",
  "Beheeyem",
  "Litwick",
  "Lampent",
  "Chandelure",
  "Axew",
  "Fraxure",
  "Haxorus",
  "Cubchoo",
  "Beartic",
  "Cryogonal",
  "Shelmet",
  "Accelgor",
  "Stunfisk",
  "Mienfoo",
  "Mienshao",
  "Druddigon",
  "Golett",
  "Golurk",
  "Pawniard",
  "Bisharp",
  "Bouffalant",
  "Rufflet",
  "Braviary",
  "Vullaby",
  "Mandibuzz",
  "Heatmor",
  "Durant",
  "Deino",
  "Zweilous",
  "Hydreigon",
  "Larvesta",
  "Volcarona",
  "Cobalion",
  "Terrakion",
  "Virizion",
  "Tornadus",
  "Thundurus",
  "Reshiram",
  "Zekrom",
  "Landorus",
  "Kyurem",
  "Keldeo",
  "Meloetta",
  "Genesect",
  "Chespin",
  "Quilladin",
  "Chesnaught",
  "Fennekin",
  "Braixen",
  "Delphox",
  "Froakie",
  "Frogadier",
  "Greninja",
  "Bunnelby",
  "Diggersby",
  "Fletchling",
  "Fletchinder",
  "Talonflame",
  "Scatterbug",
  "Spewpa",
  "Vivillon",
  "Litleo",
  "Pyroar",
  "Flabebe",
  "Floette",
  "Florges",
  "Skiddo",
  "Gogoat",
  "Pancham",
  "Pangoro",
  "Furfrou",
  "Espurr",
  "Meowstic",
  "Honedge",
  "Doublade",
  "Aegislash",
  "Spritzee",
  "Aromatisse",
  "Swirlix",
  "Slurpuff",
  "Inkay",
  "Malamar",
  "Binacle",
  "Barbaracle",
  "Skrelp",
  "Dragalge",
  "Clauncher",
  "Clawitzer",
  "Helioptile",
  "Heliolisk",
  "Tyrunt",
  "Tyrantrum",
  "Amaura",
  "Aurorus",
  "Sylveon",
  "Hawlucha",
  "Dedenne",
  "Carbink",
  "Goomy",
  "Sliggoo",
  "Goodra",
  "Klefki",
  "Phantump",
  "Trevenant",
  "Pumpkaboo",
  "Gourgeist",
  "Bergmite",
  "Avalugg",
  "Noibat",
  "Noivern",
  "Xerneas",
  "Yveltal",
  "Zygarde",
  "Diancie",
  "Hoopa",
  "Volcanion",
  "Rowlet",
  "Dartrix",
  "Decidueye",
  "Litten",
  "Torracat",
  "Incineroar",
  "Popplio",
  "Brionne",
  "Primarina",
  "Pikipek",
  "Trumbeak",
  "Toucannon",
  "Yungoos",
  "Gumshoos",
  "Grubbin",
  "Charjabug",
  "Vikavolt",
  "Crabrawler",
  "Crabominable",
  "Oricorio",
  "Cutiefly",
  "Ribombee",
  "Rockruff",
  "Lycanroc",
  "Wishiwashi",
  "Mareanie",
  "Toxapex",
  "Mudbray",
  "Mudsdale",
  "Dewpider",
  "Araquanid",
  "Fomantis",
  "Lurantis",
  "Morelull",
  "Shiinotic",
  "Salandit",
  "Salazzle",
  "Stufful",
  "Bewear",
  "Bounsweet",
  "Steenee",
  "Tsareena",
  "Comfey",
  "Oranguru",
  "Passimian",
  "Wimpod",
  "Golisopod",
  "Sandygast",
  "Palossand",
  "Pyukumuku",
  "Type: Null",
  "Silvally",
  "Minior",
  "Komala",
  "Turtonator",
  "Togedemaru",
  "Mimikyu",
  "Bruxish",
  "Drampa",
  "Dhelmise",
  "Jangmo-o",
  "Hakamo-o",
  "Kommo-o",
  "Tapu Koko",
  "Tapu Lele",
  "Tapu Bulu",
  "Tapu Fini",
  "Cosmog",
  "Cosmoem",
  "Solgaleo",
  "Lunala",
  "Nihilego",
  "Buzzwole",
  "Pheromosa",
  "Xurkitree",
  "Celesteela",
  "Kartana",
  "Guzzlord",
  "Necrozma",
  "Magearna",
  "Marshadow",
  "Poipole",
  "Naganadel",
  "Stakataka",
  "Blacephalon",
  "Zeraora"
];

'use strict';
const formes = new Array(802);
formes[0] = null;
for (let i = 1; i < formes.length; i++) {
  formes[i] = null;
}

formes[20] = [null, 'Alola', 'Totem'];
formes[25] = [null, 'Original Cap', 'Hoenn Cap', 'Sinnoh Cap', 'Unova Cap', 'Kalos Cap', 'Alola Cap', 'Partner Cap'];

formes[105] = [null, 'Alola', 'Totem'];

formes[201] = [
  'A',
  'B',
  'C',
  'D',
  'E',
  'F',
  'G',
  'H',
  'I',
  'J',
  'K',
  'L',
  'M',
  'N',
  'O',
  'P',
  'Q',
  'R',
  'S',
  'T',
  'U',
  'V',
  'W',
  'X',
  'Y',
  'Z',
  '!',
  '?'
];

formes[351] = [null, 'Sunny', 'Rainy', 'Snowy'];

[382, 383].forEach(i => {
  formes[i] = [null, 'Primal'];
});

formes[386] = [null, 'Attack', 'Defense', 'Speed'];

[412, 413].forEach(i => {
  formes[i] = ['Plant', 'Sandy', 'Trash'];
});

formes[421] = ['Overcast', 'Sunshine'];

[422, 423].forEach(i => {
  formes[i] = ['West', 'East'];
});

formes[479] = [null, 'Heat', 'Wash', 'Frost', 'Fan', 'Mow'];
formes[487] = ['Altered', 'Origin'];
formes[492] = ['Land', 'Sky'];

formes[493] = [
  null,
  'Fighting',
  'Flying',
  'Poison',
  'Ground',
  'Rock',
  'Bug',
  'Ghost',
  'Steel',
  'Fire',
  'Water',
  'Grass',
  'Electric',
  'Psychic',
  'Ice',
  'Dragon',
  'Dark',
  'Fairy'
];

formes[550] = ['Red', 'Blue'];
formes[555] = [null, 'Zen'];

[585, 586].forEach(i => {
  formes[i] = ['Spring', 'Summer', 'Autumn', 'Winter'];
});

[641, 642, 645].forEach(i => {
  formes[i] = ['Incarnate', 'Therian'];
});

formes[646] = [null, 'White', 'Black'];
formes[647] = [null, 'Resolute'];
formes[648] = ['Aria', 'Pirouette'];
formes[649] = [null, 'Douse', 'Shock', 'Burn', 'Chill'];
formes[658] = [null, 'Ash', 'Ash'];

[664, 665, 666].forEach(i => {
  formes[i] = [
    'Icy Snow',
    'Polar',
    'Tundra',
    'Continental',
    'Garden',
    'Elegant',
    'Meadow',
    'Modern',
    'Marine',
    'Archipelago',
    'High Plains',
    'Sandstorm',
    'River',
    'Monsoon',
    'Savanna',
    'Sun',
    'Ocean',
    'Jungle',
    'Fancy',
    'Poké Ball'
  ];
});

[669, 671].forEach(i => {
  formes[i] = ['Red', 'Yellow', 'Orange', 'Blue', 'White'];
});

formes[670] = ['Red', 'Yellow', 'Orange', 'Blue', 'White', 'Eternal'];
formes[676] = [null, 'Heart', 'Star', 'Diamond', 'Debutante', 'Matron', 'Dandy', 'La Reine', 'Kabuki', 'Pharaoh'];
formes[678] = [null, null];
formes[681] = ['Shield', 'Blade'];

[710, 711].forEach(i => {
  formes[i] = ['Average', 'Small', 'Large', 'Super'];
});

formes[716] = [null, 'Active'];
formes[718] = ['50%', '10%', '10%', '50%', 'Complete'];
formes[720] = ['Confined', 'Unbound'];
formes[735] = [null, 'Totem'];
formes[738] = [null, 'Totem'];
formes[741] = ['Baile', 'Pom-Pom', 'Pa’u', 'Sensu'];
formes[743] = [null, 'Totem'];
formes[744] = [null, 'Dusk'];
formes[745] = ['Midday', 'Midnight', 'Dusk'];
formes[746] = ['Solo', 'School'];
formes[752] = [null, 'Totem'];
formes[754] = [null, 'Totem'];
formes[758] = [null, 'Totem'];

formes[773] = [
  null,
  'Fighting',
  'Flying',
  'Poison',
  'Ground',
  'Rock',
  'Bug',
  'Ghost',
  'Steel',
  'Fire',
  'Water',
  'Grass',
  'Electric',
  'Psychic',
  'Ice',
  'Dragon',
  'Dark',
  'Fairy'
];

formes[774] = [
  'Meteor-Red',
  'Meteor-Orange',
  'Meteor-Yellow',
  'Meteor-Green',
  'Meteor-Blue',
  'Meteor-Indigo',
  'Meteor-Violet',
  'Red',
  'Orange',
  'Yellow',
  'Green',
  'Blue',
  'Indigo',
  'Violet'
];

formes[777] = [null, 'Totem'];
formes[778] = [null, 'Busted', 'Totem', 'Totem-Busted'];
formes[784] = [null, 'Totem'];
formes[800] = [null, 'Dusk Mane', 'Dawn Wings', 'Ultra'];
formes[801] = [null, 'Original Color'];

[
  3,
  9,
  15,
  18,
  65,
  80,
  94,
  115,
  127,
  130,
  142,
  181,
  208,
  212,
  214,
  229,
  248,
  254,
  257,
  260,
  282,
  302,
  303,
  306,
  308,
  310,
  319,
  323,
  334,
  354,
  359,
  362,
  373,
  376,
  380,
  381,
  384,
  428,
  445,
  448,
  460,
  475,
  531,
  719
].forEach(i => {
  formes[i] = [null, 'Mega'];
});

[6, 150].forEach(i => {
  formes[i] = [null, 'Mega X', 'Mega Y'];
});

[
  19,
  26,
  27,
  28,
  37,
  38,
  50,
  51,
  52,
  53,
  74,
  75,
  76,
  88,
  89,
  103
].forEach(i => {
  formes[i] = [null, 'Alola'];
});

const itemName = [
  "None",
  "Master Ball",
  "Ultra Ball",
  "Great Ball",
  "Poke Ball",
  "Safari Ball",
  "Net Ball",
  "Dive Ball",
  "Nest Ball",
  "Repeat Ball",
  "Timer Ball",
  "Luxury Ball",
  "Premier Ball",
  "Dusk Ball",
  "Heal Ball",
  "Quick Ball",
  "Cherish Ball",
  "Potion",
  "Antidote",
  "Burn Heal",
  "Ice Heal",
  "Awakening",
  "Paralyze Heal",
  "Full Restore",
  "Max Potion",
  "Hyper Potion",
  "Super Potion",
  "Full Heal",
  "Revive",
  "Max Revive",
  "Fresh Water",
  "Soda Pop",
  "Lemonade",
  "Moomoo Milk",
  "Energy Powder",
  "Energy Root",
  "Heal Powder",
  "Revival Herb",
  "Ether",
  "Max Ether",
  "Elixir",
  "Max Elixir",
  "Lava Cookie",
  "Berry Juice",
  "Sacred Ash",
  "HP Up",
  "Protein",
  "Iron",
  "Carbos",
  "Calcium",
  "Rare Candy",
  "PP Up",
  "Zinc",
  "PP Max",
  "Old Gateau",
  "Guard Spec.",
  "Dire Hit",
  "X Attack",
  "X Defense",
  "X Speed",
  "X Accuracy",
  "X Sp. Atk",
  "X Sp. Def",
  "Poke Doll",
  "Fluffy Tail",
  "Blue Flute",
  "Yellow Flute",
  "Red Flute",
  "Black Flute",
  "White Flute",
  "Shoal Salt",
  "Shoal Shell",
  "Red Shard",
  "Blue Shard",
  "Yellow Shard",
  "Green Shard",
  "Super Repel",
  "Max Repel",
  "Escape Rope",
  "Repel",
  "Sun Stone",
  "Moon Stone",
  "Fire Stone",
  "Thunder Stone",
  "Water Stone",
  "Leaf Stone",
  "Tiny Mushroom",
  "Big Mushroom",
  "Pearl",
  "Big Pearl",
  "Stardust",
  "Star Piece",
  "Nugget",
  "Heart Scale",
  "Honey",
  "Growth Mulch",
  "Damp Mulch",
  "Stable Mulch",
  "Gooey Mulch",
  "Root Fossil",
  "Claw Fossil",
  "Helix Fossil",
  "Dome Fossil",
  "Old Amber",
  "Armor Fossil",
  "Skull Fossil",
  "Rare Bone",
  "Shiny Stone",
  "Dusk Stone",
  "Dawn Stone",
  "Oval Stone",
  "Odd Keystone",
  "Griseous Orb",
  "???",
  "???",
  "???",
  "Douse Drive",
  "Shock Drive",
  "Burn Drive",
  "Chill Drive",
  "???",
  "???",
  "???",
  "???",
  "???",
  "???",
  "???",
  "???",
  "???",
  "???",
  "???",
  "???",
  "???",
  "???",
  "Sweet Heart",
  "Adamant Orb",
  "Lustrous Orb",
  "Greet Mail",
  "Favored Mail",
  "RSVP Mail",
  "Thanks Mail",
  "Inquiry Mail",
  "Like Mail",
  "Reply Mail",
  "Bridge Mail S",
  "Bridge Mail D",
  "Bridge Mail T",
  "Bridge Mail V",
  "Bridge Mail M",
  "Cheri Berry",
  "Chesto Berry",
  "Pecha Berry",
  "Rawst Berry",
  "Aspear Berry",
  "Leppa Berry",
  "Oran Berry",
  "Persim Berry",
  "Lum Berry",
  "Sitrus Berry",
  "Figy Berry",
  "Wiki Berry",
  "Mago Berry",
  "Aguav Berry",
  "Iapapa Berry",
  "Razz Berry",
  "Bluk Berry",
  "Nanab Berry",
  "Wepear Berry",
  "Pinap Berry",
  "Pomeg Berry",
  "Kelpsy Berry",
  "Qualot Berry",
  "Hondew Berry",
  "Grepa Berry",
  "Tamato Berry",
  "Cornn Berry",
  "Magost Berry",
  "Rabuta Berry",
  "Nomel Berry",
  "Spelon Berry",
  "Pamtre Berry",
  "Watmel Berry",
  "Durin Berry",
  "Belue Berry",
  "Occa Berry",
  "Passho Berry",
  "Wacan Berry",
  "Rindo Berry",
  "Yache Berry",
  "Chople Berry",
  "Kebia Berry",
  "Shuca Berry",
  "Coba Berry",
  "Payapa Berry",
  "Tanga Berry",
  "Charti Berry",
  "Kasib Berry",
  "Haban Berry",
  "Colbur Berry",
  "Babiri Berry",
  "Chilan Berry",
  "Liechi Berry",
  "Ganlon Berry",
  "Salac Berry",
  "Petaya Berry",
  "Apicot Berry",
  "Lansat Berry",
  "Starf Berry",
  "Enigma Berry",
  "Micle Berry",
  "Custap Berry",
  "Jaboca Berry",
  "Rowap Berry",
  "Bright Powder",
  "White Herb",
  "Macho Brace",
  "Exp. Share",
  "Quick Claw",
  "Soothe Bell",
  "Mental Herb",
  "Choice Band",
  "King's Rock",
  "Silver Powder",
  "Amulet Coin",
  "Cleanse Tag",
  "Soul Dew",
  "Deep Sea Tooth",
  "Deep Sea Scale",
  "Smoke Ball",
  "Everstone",
  "Focus Band",
  "Lucky Egg",
  "Scope Lens",
  "Metal Coat",
  "Leftovers",
  "Dragon Scale",
  "Light Ball",
  "Soft Sand",
  "Hard Stone",
  "Miracle Seed",
  "Black Glasses",
  "Black Belt",
  "Magnet",
  "Mystic Water",
  "Sharp Beak",
  "Poison Barb",
  "Never-Melt Ice",
  "Spell Tag",
  "Twisted Spoon",
  "Charcoal",
  "Dragon Fang",
  "Silk Scarf",
  "Up-Grade",
  "Shell Bell",
  "Sea Incense",
  "Lax Incense",
  "Lucky Punch",
  "Metal Powder",
  "Thick Club",
  "Stick",
  "Red Scarf",
  "Blue Scarf",
  "Pink Scarf",
  "Green Scarf",
  "Yellow Scarf",
  "Wide Lens",
  "Muscle Band",
  "Wise Glasses",
  "Expert Belt",
  "Light Clay",
  "Life Orb",
  "Power Herb",
  "Toxic Orb",
  "Flame Orb",
  "Quick Powder",
  "Focus Sash",
  "Zoom Lens",
  "Metronome",
  "Iron Ball",
  "Lagging Tail",
  "Destiny Knot",
  "Black Sludge",
  "Icy Rock",
  "Smooth Rock",
  "Heat Rock",
  "Damp Rock",
  "Grip Claw",
  "Choice Scarf",
  "Sticky Barb",
  "Power Bracer",
  "Power Belt",
  "Power Lens",
  "Power Band",
  "Power Anklet",
  "Power Weight",
  "Shed Shell",
  "Big Root",
  "Choice Specs",
  "Flame Plate",
  "Splash Plate",
  "Zap Plate",
  "Meadow Plate",
  "Icicle Plate",
  "Fist Plate",
  "Toxic Plate",
  "Earth Plate",
  "Sky Plate",
  "Mind Plate",
  "Insect Plate",
  "Stone Plate",
  "Spooky Plate",
  "Draco Plate",
  "Dread Plate",
  "Iron Plate",
  "Odd Incense",
  "Rock Incense",
  "Full Incense",
  "Wave Incense",
  "Rose Incense",
  "Luck Incense",
  "Pure Incense",
  "Protector",
  "Electirizer",
  "Magmarizer",
  "Dubious Disc",
  "Reaper Cloth",
  "Razor Claw",
  "Razor Fang",
  "TM01",
  "TM02",
  "TM03",
  "TM04",
  "TM05",
  "TM06",
  "TM07",
  "TM08",
  "TM09",
  "TM10",
  "TM11",
  "TM12",
  "TM13",
  "TM14",
  "TM15",
  "TM16",
  "TM17",
  "TM18",
  "TM19",
  "TM20",
  "TM21",
  "TM22",
  "TM23",
  "TM24",
  "TM25",
  "TM26",
  "TM27",
  "TM28",
  "TM29",
  "TM30",
  "TM31",
  "TM32",
  "TM33",
  "TM34",
  "TM35",
  "TM36",
  "TM37",
  "TM38",
  "TM39",
  "TM40",
  "TM41",
  "TM42",
  "TM43",
  "TM44",
  "TM45",
  "TM46",
  "TM47",
  "TM48",
  "TM49",
  "TM50",
  "TM51",
  "TM52",
  "TM53",
  "TM54",
  "TM55",
  "TM56",
  "TM57",
  "TM58",
  "TM59",
  "TM60",
  "TM61",
  "TM62",
  "TM63",
  "TM64",
  "TM65",
  "TM66",
  "TM67",
  "TM68",
  "TM69",
  "TM70",
  "TM71",
  "TM72",
  "TM73",
  "TM74",
  "TM75",
  "TM76",
  "TM77",
  "TM78",
  "TM79",
  "TM80",
  "TM81",
  "TM82",
  "TM83",
  "TM84",
  "TM85",
  "TM86",
  "TM87",
  "TM88",
  "TM89",
  "TM90",
  "TM91",
  "TM92",
  "HM01",
  "HM02",
  "HM03",
  "HM04",
  "HM05",
  "HM06",
  "???",
  "???",
  "Explorer Kit",
  "Loot Sack",
  "Rule Book",
  "Poke Radar",
  "Point Card",
  "Journal",
  "Seal Case",
  "Fashion Case",
  "Seal Bag",
  "Pal Pad",
  "Works Key",
  "Old Charm",
  "Galactic Key",
  "Red Chain",
  "Town Map",
  "Vs. Seeker",
  "Coin Case",
  "Old Rod",
  "Good Rod",
  "Super Rod",
  "Sprayduck",
  "Poffin Case",
  "Bike",
  "Suite Key",
  "Oak's Letter",
  "Lunar Wing",
  "Member Card",
  "Azure Flute",
  "S.S. Ticket",
  "Contest Pass",
  "Magma Stone",
  "Parcel",
  "Coupon 1",
  "Coupon 2",
  "Coupon 3",
  "Storage Key",
  "Secret Potion",
  "Vs. Recorder",
  "Gracidea",
  "Secret Key",
  "Apricorn Box",
  "Unown Report",
  "Berry Pots",
  "Dowsing Machine",
  "Blue Card",
  "Slowpoke Tail",
  "Clear Bell",
  "Card Key",
  "Basement Key",
  "Squirt Bottle",
  "Red Scale",
  "Lost Item",
  "Pass",
  "Machine Part",
  "Silver Wing",
  "Rainbow Wing",
  "Mystery Egg",
  "Red Apricorn",
  "Blue Apricorn",
  "Yellow Apricorn",
  "Green Apricorn",
  "Pink Apricorn",
  "White Apricorn",
  "Black Apricorn",
  "Fast Ball",
  "Level Ball",
  "Lure Ball",
  "Heavy Ball",
  "Love Ball",
  "Friend Ball",
  "Moon Ball",
  "Sport Ball",
  "Park Ball",
  "Photo Album",
  "GB Sounds",
  "Tidal Bell",
  "Rage Candy Bar",
  "Data Card 01",
  "Data Card 02",
  "Data Card 03",
  "Data Card 04",
  "Data Card 05",
  "Data Card 06",
  "Data Card 07",
  "Data Card 08",
  "Data Card 09",
  "Data Card 10",
  "Data Card 11",
  "Data Card 12",
  "Data Card 13",
  "Data Card 14",
  "Data Card 15",
  "Data Card 16",
  "Data Card 17",
  "Data Card 18",
  "Data Card 19",
  "Data Card 20",
  "Data Card 21",
  "Data Card 22",
  "Data Card 23",
  "Data Card 24",
  "Data Card 25",
  "Data Card 26",
  "Data Card 27",
  "Jade Orb",
  "Lock Capsule",
  "Red Orb",
  "Blue Orb",
  "Enigma Stone",
  "Prism Scale",
  "Eviolite",
  "Float Stone",
  "Rocky Helmet",
  "Air Balloon",
  "Red Card",
  "Ring Target",
  "Binding Band",
  "Absorb Bulb",
  "Cell Battery",
  "Eject Button",
  "Fire Gem",
  "Water Gem",
  "Electric Gem",
  "Grass Gem",
  "Ice Gem",
  "Fighting Gem",
  "Poison Gem",
  "Ground Gem",
  "Flying Gem",
  "Psychic Gem",
  "Bug Gem",
  "Rock Gem",
  "Ghost Gem",
  "Dragon Gem",
  "Dark Gem",
  "Steel Gem",
  "Normal Gem",
  "Health Wing",
  "Muscle Wing",
  "Resist Wing",
  "Genius Wing",
  "Clever Wing",
  "Swift Wing",
  "Pretty Wing",
  "Cover Fossil",
  "Plume Fossil",
  "Liberty Pass",
  "Pass Orb",
  "Dream Ball",
  "Poke Toy",
  "Prop Case",
  "Dragon Skull",
  "Balm Mushroom",
  "Big Nugget",
  "Pearl String",
  "Comet Shard",
  "Relic Copper",
  "Relic Silver",
  "Relic Gold",
  "Relic Vase",
  "Relic Band",
  "Relic Statue",
  "Relic Crown",
  "Casteliacone",
  "Dire Hit 2",
  "X Speed 2",
  "X Sp. Atk 2",
  "X Sp. Def 2",
  "X Defense 2",
  "X Attack 2",
  "X Accuracy 2",
  "X Speed 3",
  "X Sp. Atk 3",
  "X Sp. Def 3",
  "X Defense 3",
  "X Attack 3",
  "X Accuracy 3",
  "X Speed 6",
  "X Sp. Atk 6",
  "X Sp. Def 6",
  "X Defense 6",
  "X Attack 6",
  "X Accuracy 6",
  "Ability Urge",
  "Item Drop",
  "Item Urge",
  "Reset Urge",
  "Dire Hit 3",
  "Light Stone",
  "Dark Stone",
  "TM93",
  "TM94",
  "TM95",
  "Xtransceiver",
  "???",
  "Gram 1",
  "Gram 2",
  "Gram 3",
  "Xtransceiver",
  "Medal Box",
  "DNA Splicers",
  "DNA Splicers",
  "Permit",
  "Oval Charm",
  "Shiny Charm",
  "Plasma Card",
  "Grubby Hanky",
  "Colress Machine",
  "Dropped Item",
  "Dropped Item",
  "Reveal Glass",
  "Weakness Policy",
  "Assault Vest",
  "Holo Caster",
  "Prof's Letter",
  "Roller Skates",
  "Pixie Plate",
  "Ability Capsule",
  "Whipped Dream",
  "Sachet",
  "Luminous Moss",
  "Snowball",
  "Safety Goggles",
  "Poke Flute",
  "Rich Mulch",
  "Surprise Mulch",
  "Boost Mulch",
  "Amaze Mulch",
  "Gengarite",
  "Gardevoirite",
  "Ampharosite",
  "Venusaurite",
  "Charizardite X",
  "Blastoisinite",
  "Mewtwonite X",
  "Mewtwonite Y",
  "Blazikenite",
  "Medichamite",
  "Houndoominite",
  "Aggronite",
  "Banettite",
  "Tyranitarite",
  "Scizorite",
  "Pinsirite",
  "Aerodactylite",
  "Lucarionite",
  "Abomasite",
  "Kangaskhanite",
  "Gyaradosite",
  "Absolite",
  "Charizardite Y",
  "Alakazite",
  "Heracronite",
  "Mawilite",
  "Manectite",
  "Garchompite",
  "Latiasite",
  "Latiosite",
  "Roseli Berry",
  "Kee Berry",
  "Maranga Berry",
  "Sprinklotad",
  "TM96",
  "TM97",
  "TM98",
  "TM99",
  "TM100",
  "Power Plant Pass",
  "Mega Ring",
  "Intriguing Stone",
  "Common Stone",
  "Discount Coupon",
  "Elevator Key",
  "TMV Pass",
  "Honor of Kalos",
  "Adventure Rules",
  "Strange Souvenir",
  "Lens Case",
  "Makeup Bag",
  "Travel Trunk",
  "Lumiose Galette",
  "Shalour Sable",
  "Jaw Fossil",
  "Sail Fossil",
  "Looker Ticket",
  "Bike",
  "Holo Caster",
  "Fairy Gem",
  "Mega Charm",
  "Mega Glove",
  "Mach Bike",
  "Acro Bike",
  "Wailmer Pail",
  "Devon Parts",
  "Soot Sack",
  "Basement Key",
  "Pokeblock Kit",
  "Letter",
  "Eon Ticket",
  "Scanner",
  "Go-Goggles",
  "Meteorite",
  "Key to Room 1",
  "Key to Room 2",
  "Key to Room 4",
  "Key to Room 6",
  "Storage Key",
  "Devon Scope",
  "S.S. Ticket",
  "HM07",
  "Devon Scuba Gear",
  "Contest Costume",
  "Contest Costume",
  "Magma Suit",
  "Aqua Suit",
  "Pair of Tickets",
  "Mega Bracelet",
  "Mega Pendant",
  "Mega Glasses",
  "Mega Anchor",
  "Mega Stickpin",
  "Mega Tiara",
  "Mega Anklet",
  "Meteorite",
  "Swampertite",
  "Sceptilite",
  "Sablenite",
  "Altarianite",
  "Galladite",
  "Audinite",
  "Metagrossite",
  "Sharpedonite",
  "Slowbronite",
  "Steelixite",
  "Pidgeotite",
  "Glalitite",
  "Diancite",
  "Prison Bottle",
  "Mega Cuff",
  "Cameruptite",
  "Lopunnite",
  "Salamencite",
  "Beedrillite",
  "Meteorite",
  "Meteorite",
  "Key Stone",
  "Meteorite Shard",
  "Eon Flute",
  "Normalium Z",
  "Firium Z",
  "Waterium Z",
  "Electrium Z",
  "Grassium Z",
  "Icium Z",
  "Fightinium Z",
  "Poisonium Z",
  "Groundium Z",
  "Flyinium Z",
  "Psychium Z",
  "Buginium Z",
  "Rockium Z",
  "Ghostium Z",
  "Dragonium Z",
  "Darkinium Z",
  "Steelium Z",
  "Fairium Z",
  "Pikanium Z",
  "Bottle Cap",
  "Gold Bottle Cap",
  "Z-Ring",
  "Decidium Z",
  "Incinium Z",
  "Primarium Z",
  "Tapunium Z",
  "Marshadium Z",
  "Aloraichium Z",
  "Snorlium Z",
  "Eevium Z",
  "Mewnium Z",
  "Normalium Z",
  "Firium Z",
  "Waterium Z",
  "Electrium Z",
  "Grassium Z",
  "Icium Z",
  "Fightinium Z",
  "Poisonium Z",
  "Groundium Z",
  "Flyinium Z",
  "Psychium Z",
  "Buginium Z",
  "Rockium Z",
  "Ghostium Z",
  "Dragonium Z",
  "Darkinium Z",
  "Steelium Z",
  "Fairium Z",
  "Pikanium Z",
  "Decidium Z",
  "Incinium Z",
  "Primarium Z",
  "Tapunium Z",
  "Marshadium Z",
  "Aloraichium Z",
  "Snorlium Z",
  "Eevium Z",
  "Mewnium Z",
  "Pikashunium Z",
  "Pikashunium Z",
  "???",
  "???",
  "???",
  "???",
  "Forage Bag",
  "Fishing Rod",
  "Professor's Mask",
  "Festival Ticket",
  "Sparkling Stone",
  "Adrenaline Orb",
  "Zygarde Cube",
  "???",
  "Ice Stone",
  "Ride Pager",
  "Beast Ball",
  "Big Malasada",
  "Red Nectar",
  "Yellow Nectar",
  "Pink Nectar",
  "Purple Nectar",
  "Sun Flute",
  "Moon Flute",
  "???",
  "Enigmatic Card",
  "???",
  "???",
  "???",
  "???",
  "???",
  "???",
  "???",
  "???",
  "???",
  "???",
  "???",
  "???",
  "???",
  "???",
  "???",
  "???",
  "???",
  "???",
  "Terrain Extender",
  "Protective Pads",
  "Electric Seed",
  "Psychic Seed",
  "Misty Seed",
  "Grassy Seed",
  "???",
  "???",
  "???",
  "???",
  "???",
  "???",
  "???",
  "???",
  "???",
  "???",
  "???",
  "???",
  "???",
  "???",
  "???",
  "???",
  "???",
  "???",
  "???",
  "Fighting Memory",
  "Flying Memory",
  "Poison Memory",
  "Ground Memory",
  "Rock Memory",
  "Bug Memory",
  "Ghost Memory",
  "Steel Memory",
  "Fire Memory",
  "Water Memory",
  "Grass Memory",
  "Electric Memory",
  "Psychic Memory",
  "Ice Memory",
  "Dragon Memory",
  "Dark Memory",
  "Fairy Memory",
  "Solganium Z",
  "Lunalium Z",
  "Ultranecrozium Z",
  "Mimikium Z",
  "Lycanium Z",
  "Kommonium Z",
  "Solganium Z",
  "Lunalium Z",
  "Ultranecrozium Z",
  "Mimikium Z",
  "Lycanium Z",
  "Kommonium Z",
  "Z-Power Ring",
  "Pink Petal",
  "Orange Petal",
  "Blue Petal",
  "Red Petal",
  "Green Petal",
  "Yellow Petal",
  "Purple Petal",
  "Rainbow Flower",
  "Surge Badge",
  "N-Solarizer",
  "N-Lunarizer",
  "N-Solarizer",
  "N-Lunarizer",
  "Ilima's Normalium Z",
  "Left Poké Ball",
  "Roto Hatch",
  "Roto Bargain",
  "Roto Prize Money",
  "Roto Exp. Points",
  "Roto Friendship",
  "Roto Encounter",
  "Roto Stealth",
  "Roto HP Restore",
  "Roto PP Restore",
  "Roto Boost",
  "Roto Catch"
];

const ballName = [
  "",
  "Master Ball",
  "Ultra Ball",
  "Great Ball",
  "Poke Ball",
  "Safari Ball",
  "Net Ball",
  "Dive Ball",
  "Nest Ball",
  "Repeat Ball",
  "Timer Ball",
  "Luxury Ball",
  "Premier Ball",
  "Dusk Ball",
  "Heal Ball",
  "Quick Ball",
  "Cherish Ball",
  "Fast Ball",
  "Level Ball",
  "Lure Ball",
  "Heavy Ball",
  "Love Ball",
  "Friend Ball",
  "Moon Ball",
  "Sport Ball",
  "Dream Ball",
  "Beast Ball",
];

const moveName = [
  "",
  "Pound",
  "Karate Chop",
  "Double Slap",
  "Comet Punch",
  "Mega Punch",
  "Pay Day",
  "Fire Punch",
  "Ice Punch",
  "Thunder Punch",
  "Scratch",
  "Vice Grip",
  "Guillotine",
  "Razor Wind",
  "Swords Dance",
  "Cut",
  "Gust",
  "Wing Attack",
  "Whirlwind",
  "Fly",
  "Bind",
  "Slam",
  "Vine Whip",
  "Stomp",
  "Double Kick",
  "Mega Kick",
  "Jump Kick",
  "Rolling Kick",
  "Sand Attack",
  "Headbutt",
  "Horn Attack",
  "Fury Attack",
  "Horn Drill",
  "Tackle",
  "Body Slam",
  "Wrap",
  "Take Down",
  "Thrash",
  "Double-Edge",
  "Tail Whip",
  "Poison Sting",
  "Twineedle",
  "Pin Missile",
  "Leer",
  "Bite",
  "Growl",
  "Roar",
  "Sing",
  "Supersonic",
  "Sonic Boom",
  "Disable",
  "Acid",
  "Ember",
  "Flamethrower",
  "Mist",
  "Water Gun",
  "Hydro Pump",
  "Surf",
  "Ice Beam",
  "Blizzard",
  "Psybeam",
  "Bubble Beam",
  "Aurora Beam",
  "Hyper Beam",
  "Peck",
  "Drill Peck",
  "Submission",
  "Low Kick",
  "Counter",
  "Seismic Toss",
  "Strength",
  "Absorb",
  "Mega Drain",
  "Leech Seed",
  "Growth",
  "Razor Leaf",
  "Solar Beam",
  "Poison Powder",
  "Stun Spore",
  "Sleep Powder",
  "Petal Dance",
  "String Shot",
  "Dragon Rage",
  "Fire Spin",
  "Thunder Shock",
  "Thunderbolt",
  "Thunder Wave",
  "Thunder",
  "Rock Throw",
  "Earthquake",
  "Fissure",
  "Dig",
  "Toxic",
  "Confusion",
  "Psychic",
  "Hypnosis",
  "Meditate",
  "Agility",
  "Quick Attack",
  "Rage",
  "Teleport",
  "Night Shade",
  "Mimic",
  "Screech",
  "Double Team",
  "Recover",
  "Harden",
  "Minimize",
  "Smokescreen",
  "Confuse Ray",
  "Withdraw",
  "Defense Curl",
  "Barrier",
  "Light Screen",
  "Haze",
  "Reflect",
  "Focus Energy",
  "Bide",
  "Metronome",
  "Mirror Move",
  "Self-Destruct",
  "Egg Bomb",
  "Lick",
  "Smog",
  "Sludge",
  "Bone Club",
  "Fire Blast",
  "Waterfall",
  "Clamp",
  "Swift",
  "Skull Bash",
  "Spike Cannon",
  "Constrict",
  "Amnesia",
  "Kinesis",
  "Soft-Boiled",
  "High Jump Kick",
  "Glare",
  "Dream Eater",
  "Poison Gas",
  "Barrage",
  "Leech Life",
  "Lovely Kiss",
  "Sky Attack",
  "Transform",
  "Bubble",
  "Dizzy Punch",
  "Spore",
  "Flash",
  "Psywave",
  "Splash",
  "Acid Armor",
  "Crabhammer",
  "Explosion",
  "Fury Swipes",
  "Bonemerang",
  "Rest",
  "Rock Slide",
  "Hyper Fang",
  "Sharpen",
  "Conversion",
  "Tri Attack",
  "Super Fang",
  "Slash",
  "Substitute",
  "Struggle",
  "Sketch",
  "Triple Kick",
  "Thief",
  "Spider Web",
  "Mind Reader",
  "Nightmare",
  "Flame Wheel",
  "Snore",
  "Curse",
  "Flail",
  "Conversion 2",
  "Aeroblast",
  "Cotton Spore",
  "Reversal",
  "Spite",
  "Powder Snow",
  "Protect",
  "Mach Punch",
  "Scary Face",
  "Feint Attack",
  "Sweet Kiss",
  "Belly Drum",
  "Sludge Bomb",
  "Mud-Slap",
  "Octazooka",
  "Spikes",
  "Zap Cannon",
  "Foresight",
  "Destiny Bond",
  "Perish Song",
  "Icy Wind",
  "Detect",
  "Bone Rush",
  "Lock-On",
  "Outrage",
  "Sandstorm",
  "Giga Drain",
  "Endure",
  "Charm",
  "Rollout",
  "False Swipe",
  "Swagger",
  "Milk Drink",
  "Spark",
  "Fury Cutter",
  "Steel Wing",
  "Mean Look",
  "Attract",
  "Sleep Talk",
  "Heal Bell",
  "Return",
  "Present",
  "Frustration",
  "Safeguard",
  "Pain Split",
  "Sacred Fire",
  "Magnitude",
  "Dynamic Punch",
  "Megahorn",
  "Dragon Breath",
  "Baton Pass",
  "Encore",
  "Pursuit",
  "Rapid Spin",
  "Sweet Scent",
  "Iron Tail",
  "Metal Claw",
  "Vital Throw",
  "Morning Sun",
  "Synthesis",
  "Moonlight",
  "Hidden Power",
  "Cross Chop",
  "Twister",
  "Rain Dance",
  "Sunny Day",
  "Crunch",
  "Mirror Coat",
  "Psych Up",
  "Extreme Speed",
  "Ancient Power",
  "Shadow Ball",
  "Future Sight",
  "Rock Smash",
  "Whirlpool",
  "Beat Up",
  "Fake Out",
  "Uproar",
  "Stockpile",
  "Spit Up",
  "Swallow",
  "Heat Wave",
  "Hail",
  "Torment",
  "Flatter",
  "Will-O-Wisp",
  "Memento",
  "Facade",
  "Focus Punch",
  "Smelling Salts",
  "Follow Me",
  "Nature Power",
  "Charge",
  "Taunt",
  "Helping Hand",
  "Trick",
  "Role Play",
  "Wish",
  "Assist",
  "Ingrain",
  "Superpower",
  "Magic Coat",
  "Recycle",
  "Revenge",
  "Brick Break",
  "Yawn",
  "Knock Off",
  "Endeavor",
  "Eruption",
  "Skill Swap",
  "Imprison",
  "Refresh",
  "Grudge",
  "Snatch",
  "Secret Power",
  "Dive",
  "Arm Thrust",
  "Camouflage",
  "Tail Glow",
  "Luster Purge",
  "Mist Ball",
  "Feather Dance",
  "Teeter Dance",
  "Blaze Kick",
  "Mud Sport",
  "Ice Ball",
  "Needle Arm",
  "Slack Off",
  "Hyper Voice",
  "Poison Fang",
  "Crush Claw",
  "Blast Burn",
  "Hydro Cannon",
  "Meteor Mash",
  "Astonish",
  "Weather Ball",
  "Aromatherapy",
  "Fake Tears",
  "Air Cutter",
  "Overheat",
  "Odor Sleuth",
  "Rock Tomb",
  "Silver Wind",
  "Metal Sound",
  "Grass Whistle",
  "Tickle",
  "Cosmic Power",
  "Water Spout",
  "Signal Beam",
  "Shadow Punch",
  "Extrasensory",
  "Sky Uppercut",
  "Sand Tomb",
  "Sheer Cold",
  "Muddy Water",
  "Bullet Seed",
  "Aerial Ace",
  "Icicle Spear",
  "Iron Defense",
  "Block",
  "Howl",
  "Dragon Claw",
  "Frenzy Plant",
  "Bulk Up",
  "Bounce",
  "Mud Shot",
  "Poison Tail",
  "Covet",
  "Volt Tackle",
  "Magical Leaf",
  "Water Sport",
  "Calm Mind",
  "Leaf Blade",
  "Dragon Dance",
  "Rock Blast",
  "Shock Wave",
  "Water Pulse",
  "Doom Desire",
  "Psycho Boost",
  "Roost",
  "Gravity",
  "Miracle Eye",
  "Wake-Up Slap",
  "Hammer Arm",
  "Gyro Ball",
  "Healing Wish",
  "Brine",
  "Natural Gift",
  "Feint",
  "Pluck",
  "Tailwind",
  "Acupressure",
  "Metal Burst",
  "U-turn",
  "Close Combat",
  "Payback",
  "Assurance",
  "Embargo",
  "Fling",
  "Psycho Shift",
  "Trump Card",
  "Heal Block",
  "Wring Out",
  "Power Trick",
  "Gastro Acid",
  "Lucky Chant",
  "Me First",
  "Copycat",
  "Power Swap",
  "Guard Swap",
  "Punishment",
  "Last Resort",
  "Worry Seed",
  "Sucker Punch",
  "Toxic Spikes",
  "Heart Swap",
  "Aqua Ring",
  "Magnet Rise",
  "Flare Blitz",
  "Force Palm",
  "Aura Sphere",
  "Rock Polish",
  "Poison Jab",
  "Dark Pulse",
  "Night Slash",
  "Aqua Tail",
  "Seed Bomb",
  "Air Slash",
  "X-Scissor",
  "Bug Buzz",
  "Dragon Pulse",
  "Dragon Rush",
  "Power Gem",
  "Drain Punch",
  "Vacuum Wave",
  "Focus Blast",
  "Energy Ball",
  "Brave Bird",
  "Earth Power",
  "Switcheroo",
  "Giga Impact",
  "Nasty Plot",
  "Bullet Punch",
  "Avalanche",
  "Ice Shard",
  "Shadow Claw",
  "Thunder Fang",
  "Ice Fang",
  "Fire Fang",
  "Shadow Sneak",
  "Mud Bomb",
  "Psycho Cut",
  "Zen Headbutt",
  "Mirror Shot",
  "Flash Cannon",
  "Rock Climb",
  "Defog",
  "Trick Room",
  "Draco Meteor",
  "Discharge",
  "Lava Plume",
  "Leaf Storm",
  "Power Whip",
  "Rock Wrecker",
  "Cross Poison",
  "Gunk Shot",
  "Iron Head",
  "Magnet Bomb",
  "Stone Edge",
  "Captivate",
  "Stealth Rock",
  "Grass Knot",
  "Chatter",
  "Judgment",
  "Bug Bite",
  "Charge Beam",
  "Wood Hammer",
  "Aqua Jet",
  "Attack Order",
  "Defend Order",
  "Heal Order",
  "Head Smash",
  "Double Hit",
  "Roar of Time",
  "Spacial Rend",
  "Lunar Dance",
  "Crush Grip",
  "Magma Storm",
  "Dark Void",
  "Seed Flare",
  "Ominous Wind",
  "Shadow Force",
  "Hone Claws",
  "Wide Guard",
  "Guard Split",
  "Power Split",
  "Wonder Room",
  "Psyshock",
  "Venoshock",
  "Autotomize",
  "Rage Powder",
  "Telekinesis",
  "Magic Room",
  "Smack Down",
  "Storm Throw",
  "Flame Burst",
  "Sludge Wave",
  "Quiver Dance",
  "Heavy Slam",
  "Synchronoise",
  "Electro Ball",
  "Soak",
  "Flame Charge",
  "Coil",
  "Low Sweep",
  "Acid Spray",
  "Foul Play",
  "Simple Beam",
  "Entrainment",
  "After You",
  "Round",
  "Echoed Voice",
  "Chip Away",
  "Clear Smog",
  "Stored Power",
  "Quick Guard",
  "Ally Switch",
  "Scald",
  "Shell Smash",
  "Heal Pulse",
  "Hex",
  "Sky Drop",
  "Shift Gear",
  "Circle Throw",
  "Incinerate",
  "Quash",
  "Acrobatics",
  "Reflect Type",
  "Retaliate",
  "Final Gambit",
  "Bestow",
  "Inferno",
  "Water Pledge",
  "Fire Pledge",
  "Grass Pledge",
  "Volt Switch",
  "Struggle Bug",
  "Bulldoze",
  "Frost Breath",
  "Dragon Tail",
  "Work Up",
  "Electroweb",
  "Wild Charge",
  "Drill Run",
  "Dual Chop",
  "Heart Stamp",
  "Horn Leech",
  "Sacred Sword",
  "Razor Shell",
  "Heat Crash",
  "Leaf Tornado",
  "Steamroller",
  "Cotton Guard",
  "Night Daze",
  "Psystrike",
  "Tail Slap",
  "Hurricane",
  "Head Charge",
  "Gear Grind",
  "Searing Shot",
  "Techno Blast",
  "Relic Song",
  "Secret Sword",
  "Glaciate",
  "Bolt Strike",
  "Blue Flare",
  "Fiery Dance",
  "Freeze Shock",
  "Ice Burn",
  "Snarl",
  "Icicle Crash",
  "V-create",
  "Fusion Flare",
  "Fusion Bolt",
  "Flying Press",
  "Mat Block",
  "Belch",
  "Rototiller",
  "Sticky Web",
  "Fell Stinger",
  "Phantom Force",
  "Trick-or-Treat",
  "Noble Roar",
  "Ion Deluge",
  "Parabolic Charge",
  "Forest's Curse",
  "Petal Blizzard",
  "Freeze-Dry",
  "Disarming Voice",
  "Parting Shot",
  "Topsy-Turvy",
  "Draining Kiss",
  "Crafty Shield",
  "Flower Shield",
  "Grassy Terrain",
  "Misty Terrain",
  "Electrify",
  "Play Rough",
  "Fairy Wind",
  "Moonblast",
  "Boomburst",
  "Fairy Lock",
  "King's Shield",
  "Play Nice",
  "Confide",
  "Diamond Storm",
  "Steam Eruption",
  "Hyperspace Hole",
  "Water Shuriken",
  "Mystical Fire",
  "Spiky Shield",
  "Aromatic Mist",
  "Eerie Impulse",
  "Venom Drench",
  "Powder",
  "Geomancy",
  "Magnetic Flux",
  "Happy Hour",
  "Electric Terrain",
  "Dazzling Gleam",
  "Celebrate",
  "Hold Hands",
  "Baby-Doll Eyes",
  "Nuzzle",
  "Hold Back",
  "Infestation",
  "Power-Up Punch",
  "Oblivion Wing",
  "Thousand Arrows",
  "Thousand Waves",
  "Land's Wrath",
  "Light of Ruin",
  "Origin Pulse",
  "Precipice Blades",
  "Dragon Ascent",
  "Hyperspace Fury",
  "Breakneck Blitz",
  "Breakneck Blitz",
  "All-Out Pummeling",
  "All-Out Pummeling",
  "Supersonic Skystrike",
  "Supersonic Skystrike",
  "Acid Downpour",
  "Acid Downpour",
  "Tectonic Rage",
  "Tectonic Rage",
  "Continental Crush",
  "Continental Crush",
  "Savage Spin-Out",
  "Savage Spin-Out",
  "Never-Ending Nightmare",
  "Never-Ending Nightmare",
  "Corkscrew Crash",
  "Corkscrew Crash",
  "Inferno Overdrive",
  "Inferno Overdrive",
  "Hydro Vortex",
  "Hydro Vortex",
  "Bloom Doom",
  "Bloom Doom",
  "Gigavolt Havoc",
  "Gigavolt Havoc",
  "Shattered Psyche",
  "Shattered Psyche",
  "Subzero Slammer",
  "Subzero Slammer",
  "Devastating Drake",
  "Devastating Drake",
  "Black Hole Eclipse",
  "Black Hole Eclipse",
  "Twinkle Tackle",
  "Twinkle Tackle",
  "Catastropika",
  "Shore Up",
  "First Impression",
  "Baneful Bunker",
  "Spirit Shackle",
  "Darkest Lariat",
  "Sparkling Aria",
  "Ice Hammer",
  "Floral Healing",
  "High Horsepower",
  "Strength Sap",
  "Solar Blade",
  "Leafage",
  "Spotlight",
  "Toxic Thread",
  "Laser Focus",
  "Gear Up",
  "Throat Chop",
  "Pollen Puff",
  "Anchor Shot",
  "Psychic Terrain",
  "Lunge",
  "Fire Lash",
  "Power Trip",
  "Burn Up",
  "Speed Swap",
  "Smart Strike",
  "Purify",
  "Revelation Dance",
  "Core Enforcer",
  "Trop Kick",
  "Instruct",
  "Beak Blast",
  "Clanging Scales",
  "Dragon Hammer",
  "Brutal Swing",
  "Aurora Veil",
  "Sinister Arrow Raid",
  "Malicious Moonsault",
  "Oceanic Operetta",
  "Guardian of Alola",
  "Soul-Stealing 7-Star Strike",
  "Stoked Sparksurfer",
  "Pulverizing Pancake",
  "Extreme Evoboost",
  "Genesis Supernova",
  "Shell Trap",
  "Fleur Cannon",
  "Psychic Fangs",
  "Stomping Tantrum",
  "Shadow Bone",
  "Accelerock",
  "Liquidation",
  "Prismatic Laser",
  "Spectral Thief",
  "Sunsteel Strike",
  "Moongeist Beam",
  "Tearful Look",
  "Zing Zap",
  "Nature's Madness",
  "Multi-Attack",
  "10,000,000 Volt Thunderbolt",
  "Mind Blown",
  "Plasma Fists",
  "Photon Geyser",
  "Light That Burns the Sky",
  "Searing Sunraze Smash",
  "Menacing Moonraze Maelstrom",
  "Let's Snuggle Forever",
  "Splintered Stormshards",
  "Clangorous Soulblaze",
];

const natureName = [
  'Hardy',
  'Lonely',
  'Brave',
  'Adamant',
  'Naughty',
  'Bold',
  'Docile',
  'Relaxed',
  'Impish',
  'Lax',
  'Timid',
  'Hasty',
  'Serious',
  'Jolly',
  'Naive',
  'Modest',
  'Mild',
  'Quiet',
  'Bashful',
  'Rash',
  'Calm',
  'Gentle',
  'Sassy',
  'Careful',
  'Quirky'
];

var locationName5, location5;
locationName5 = {
  "0": "",
  "40001": "Lovely place",
  "40002": "Faraway place",
  "40003": "Pokémon Movie",
  "40004": "Pokémon Movie 10",
  "40005": "Pokémon Movie 11",
  "40006": "Pokémon Movie 12",
  "40007": "Pokémon Movie 13",
  "40008": "Pokémon Movie 14",
  "40009": "Pokémon Movie 15",
  "40010": "Pokémon Movie 16",
  "40011": "Pokémon Movie 17",
  "40012": "Pokémon Movie 18",
  "40013": "Pokémon Movie 19",
  "40014": "Pokémon Movie 20",
  "40015": "Pokémon Center",
  "40016": "Pokémon Cartoon",
  "40017": "PC Tokyo",
  "40018": "PC Osaka",
  "40019": "PC Fukuoka",
  "40020": "PC Nagoya",
  "40021": "PC Sapporo",
  "40022": "PC Yokohama",
  "40023": "WCS",
  "40024": "WCS 2010",
  "40025": "WCS 2011",
  "40026": "WCS 2012",
  "40027": "WCS 2013",
  "40028": "WCS 2014",
  "40029": "WCS 2015",
  "40030": "WCS 2016",
  "40031": "WCS 2017",
  "40032": "WCS 2018",
  "40033": "WCS 2019",
  "40034": "WCS 2020",
  "40035": "Worlds",
  "40036": "Worlds 2010",
  "40037": "Worlds 2011",
  "40038": "Worlds 2012",
  "40039": "Worlds 2013",
  "40040": "Worlds 2014",
  "40041": "Worlds 2015",
  "40042": "Worlds 2016",
  "40043": "Worlds 2017",
  "40044": "Worlds 2018",
  "40045": "Worlds 2019",
  "40046": "Worlds 2020",
  "40047": "VGE",
  "40048": "VGE 2010",
  "40049": "VGE 2011",
  "40050": "VGE 2012",
  "40051": "VGE 2013",
  "40052": "VGE 2014",
  "40053": "VGE 2015",
  "40054": "VGE 2016",
  "40055": "VGE 2017",
  "40056": "VGE 2018",
  "40057": "VGE 2019",
  "40058": "VGE 2020",
  "40059": "Pokémon Event",
  "40060": "Battle Competition",
  "40061": "Game Event",
  "40062": "Pokémon Fan Club",
  "40063": "Pokémon Sunday",
  "40064": "Challenge Plaza",
  "40065": "Battle Challenge",
  "40066": "Trainers' Court",
  "40067": "Battle Tour",
  "40068": "Concert",
  "40069": "Wi-Fi Gift",
  "40070": "Pokémon Ranger",
  "40071": "Ranger Union",
  "40072": "PBR",
  "40073": "Pokémon DW",
  "40074": "Pokémon Event 10",
  "40075": "Pokémon Event 11",
  "40076": "Pokémon Event 12",
  "40077": "Pokémon Event 13",
  "40078": "Pokémon Event 14",
  "40079": "Pokémon Event 15",
  "40080": "Pokémon Event 16",
  "40081": "Pokémon Event 17",
  "40082": "Pokémon Event 18",
  "40083": "Pokémon Event 19",
  "40084": "Pokémon Event 20",
  "40085": "Pokémon Festa",
  "40086": "Pokémon Festa 10",
  "40087": "Pokémon Festa 11",
  "40088": "Pokémon Festa 12",
  "40089": "Pokémon Festa 13",
  "40090": "Pokémon Festa 14",
  "40091": "Pokémon Festa 15",
  "40092": "Pokémon Festa 16",
  "40093": "Pokémon Festa 17",
  "40094": "Pokémon Festa 18",
  "40095": "Pokémon Festa 19",
  "40096": "Pokémon Festa 20",
  "40097": "POKÉPARK",
  "40098": "POKÉPARK",
  "40099": "POKÉPARK",
  "40100": "POKÉPARK",
  "40101": "POKÉPARK",
  "40102": "POKÉPARK",
  "40103": "POKÉPARK",
  "40104": "POKÉPARK",
  "40105": "POKÉPARK",
  "40106": "POKÉPARK",
  "40107": "POKÉPARK",
  "40108": "POKÉPARK",
  "40109": "Event Site"
};

var locationName6, location6;
locationName6 = {
  "0": "",
  "2": "Mystery Zone",
  "4": "Faraway place",
  "6": "Vaniville Town",
  "8": "Route 1",
  "9": "Vaniville Pathway",
  "10": "Aquacorde Town",
  "12": "Route 2",
  "13": "Avance Trail",
  "14": "Santalune Forest",
  "16": "Route 3",
  "17": "Ouvert Way",
  "18": "Santalune City",
  "20": "Route 4",
  "21": "Parterre Way",
  "22": "Lumiose City",
  "24": "Lumiose Gym",
  "26": "Lysandre Labs",
  "28": "Route 5",
  "29": "Versant Road",
  "30": "Camphrier Town",
  "32": "Shabboneau Castle",
  "34": "Route 6",
  "35": "Palais Lane",
  "36": "Parfum Palace",
  "38": "Route 7",
  "39": "Rivière Walk",
  "40": "Cyllage City",
  "42": "Route 8",
  "43": "Muraille Coast",
  "44": "Ambrette Town",
  "46": "Route 9",
  "47": "Spikes Passage",
  "48": "Battle Chateau",
  "50": "Route 10",
  "51": "Menhir Trail",
  "52": "Geosenge Town",
  "54": "Route 11",
  "55": "Miroir Way",
  "56": "Reflection Cave",
  "58": "Shalour City",
  "60": "Tower of Mastery",
  "62": "Route 12",
  "63": "Fourrage Road",
  "64": "Coumarine City",
  "66": "Route 13",
  "67": "Lumiose Badlands",
  "68": "Route 14",
  "69": "Laverre Nature Trail",
  "70": "Laverre City",
  "72": "Poké Ball Factory",
  "74": "Route 15",
  "75": "Brun Way",
  "76": "Dendemille Town",
  "78": "Route 16",
  "79": "Mélancolie Path",
  "82": "Frost Cavern",
  "84": "Route 17",
  "85": "Mamoswine Road",
  "86": "Anistar City",
  "88": "Route 18",
  "89": "Vallée Étroite Way",
  "90": "Couriway Town",
  "92": "Route 19",
  "93": "Grande Vallée Way",
  "94": "Snowbelle City",
  "96": "Route 20",
  "97": "Winding Woods",
  "98": "Pokémon Village",
  "100": "Route 21",
  "101": "Dernière Way",
  "102": "Route 22",
  "103": "Détourner Way",
  "104": "Victory Road",
  "106": "Pokémon League",
  "108": "Kiloude City",
  "110": "Battle Maison",
  "112": "Azure Bay",
  "114": "Gate",
  "116": "Gate",
  "118": "Gate",
  "120": "Gate",
  "122": "Gate",
  "124": "Gate",
  "126": "Gate",
  "128": "Gate",
  "130": "Gate",
  "132": "Glittering Cave",
  "134": "Connecting Cave",
  "135": "Connecting Cave",
  "136": "Kalos Power Plant",
  "138": "Team Flare Secret HQ",
  "140": "Terminus Cave",
  "142": "Lost Hotel",
  "144": "Chamber of Emptiness",
  "146": "Sea Spirit's Den",
  "148": "Friend Safari",
  "150": "Blazing Chamber",
  "152": "Flood Chamber",
  "154": "Ironworks Chamber",
  "156": "Dragonmark Chamber",
  "158": "Radiant Chamber",
  "160": "Pokémon League Gate",
  "162": "Lumiose Station",
  "164": "Kiloude Station",
  "166": "Ambrette Aquarium",
  "168": "Unknown Dungeon",
  "170": "Littleroot Town",
  "172": "Oldale Town",
  "174": "Dewford Town",
  "176": "Lavaridge Town",
  "178": "Fallarbor Town",
  "180": "Verdanturf Town",
  "182": "Pacifidlog Town",
  "184": "Petalburg City",
  "186": "Slateport City",
  "188": "Mauville City",
  "190": "Rustboro City",
  "192": "Fortree City",
  "194": "Lilycove City",
  "196": "Mossdeep City",
  "198": "Sootopolis City",
  "200": "Ever Grande City",
  "202": "Pokémon League",
  "204": "Route 101",
  "206": "Route 102",
  "208": "Route 103",
  "210": "Route 104",
  "212": "Route 105",
  "214": "Route 106",
  "216": "Route 107",
  "218": "Route 108",
  "220": "Route 109",
  "222": "Route 110",
  "224": "Route 111",
  "226": "Route 112",
  "228": "Route 113",
  "230": "Route 114",
  "232": "Route 115",
  "234": "Route 116",
  "236": "Route 117",
  "238": "Route 118",
  "240": "Route 119",
  "242": "Route 120",
  "244": "Route 121",
  "246": "Route 122",
  "248": "Route 123",
  "250": "Route 124",
  "252": "Route 125",
  "254": "Route 126",
  "256": "Route 127",
  "258": "Route 128",
  "260": "Route 129",
  "262": "Route 130",
  "264": "Route 131",
  "266": "Route 132",
  "268": "Route 133",
  "270": "Route 134",
  "272": "Meteor Falls",
  "274": "Rusturf Tunnel",
  "276": "???",
  "278": "Desert Ruins",
  "280": "Granite Cave",
  "282": "Petalburg Woods",
  "284": "Mt. Chimney",
  "286": "Jagged Pass",
  "288": "Fiery Path",
  "290": "Mt. Pyre",
  "292": "Team Aqua Hideout",
  "294": "Seafloor Cavern",
  "296": "Cave of Origin",
  "298": "Victory Road",
  "300": "Shoal Cave",
  "302": "New Mauville",
  "304": "Sea Mauville",
  "306": "Island Cave",
  "308": "Ancient Tomb",
  "310": "Sealed Chamber",
  "312": "Scorched Slab",
  "314": "Team Magma Hideout",
  "316": "Sky Pillar",
  "318": "Battle Resort",
  "320": "Southern Island",
  "322": "S.S. Tidal",
  "324": "Safari Zone",
  "326": "Mirage Forests",
  "328": "Mirage Caves",
  "330": "Mirage Islands",
  "332": "Mirage Mountains",
  "334": "Trackless Forest",
  "336": "Pathless Plain",
  "338": "Nameless Cavern",
  "340": "Fabled Cave",
  "342": "Gnarled Den",
  "344": "Crescent Isle",
  "346": "Secret Islet",
  "348": "Soaring in the sky",
  "350": "Secret Shore",
  "352": "Secret Meadow",
  "354": "Secret Base",
  "30001": "a Link Trade",
  "30002": "a Link Trade",
  "30003": "the Kanto region",
  "30004": "the Johto region",
  "30005": "the Hoenn region",
  "30006": "the Sinnoh region",
  "30007": "a distant land",
  "30008": "----------",
  "30009": "the Unova region",
  "30010": "the Kalos region",
  "30011": "Pokémon Link",
  "40001": "a lovely place",
  "40002": "a faraway place",
  "40003": "a Pokémon movie",
  "40004": "Pokémon Movie 13",
  "40005": "Pokémon Movie 14",
  "40006": "Pokémon Movie 15",
  "40007": "Pokémon Movie 16",
  "40008": "Pokémon Movie 17",
  "40009": "Pokémon Movie 18",
  "40010": "a Pokémon Center",
  "40011": "the Pokémon cartoon",
  "40012": "PC Tokyo",
  "40013": "PC Osaka",
  "40014": "PC Fukuoka",
  "40015": "PC Nagoya",
  "40016": "PC Sapporo",
  "40017": "PC Yokohama",
  "40018": "PC Tohoku",
  "40019": "PC Tokyo Bay",
  "40020": "a Pokémon Store",
  "40021": "a WCS",
  "40022": "WCS 2013",
  "40023": "WCS 2014",
  "40024": "WCS 2015",
  "40025": "WCS 2016",
  "40026": "WCS 2017",
  "40027": "WCS 2018",
  "40028": "Worlds",
  "40029": "Worlds 2013",
  "40030": "Worlds 2014",
  "40031": "Worlds 2015",
  "40032": "Worlds 2016",
  "40033": "Worlds 2017",
  "40034": "Worlds 2018",
  "40035": "a VGE",
  "40036": "VGE 2013",
  "40037": "VGE 2014",
  "40038": "VGE 2015",
  "40039": "VGE 2016",
  "40040": "VGE 2017",
  "40041": "VGE 2018",
  "40042": "a Pokémon event",
  "40043": "a Battle Competition",
  "40044": "a game event",
  "40045": "the Pokémon Fan Club",
  "40046": "a Pokémon TV program",
  "40047": "a concert",
  "40048": "an online Present",
  "40049": "the PGL",
  "40050": "Pokémon Event 13",
  "40051": "Pokémon Event 14",
  "40052": "Pokémon Event 15",
  "40053": "Pokémon Event 16",
  "40054": "Pokémon Event 17",
  "40055": "Pokémon Event 18",
  "40056": "Pokémon Festa",
  "40057": "Pokémon Festa 13",
  "40058": "Pokémon Festa 14",
  "40059": "Pokémon Festa 15",
  "40060": "Pokémon Festa 16",
  "40061": "Pokémon Festa 17",
  "40062": "Pokémon Festa 18",
  "40063": "POKÉPARK",
  "40064": "POKÉPARK",
  "40065": "POKÉPARK",
  "40066": "POKÉPARK",
  "40067": "POKÉPARK",
  "40068": "POKÉPARK",
  "40069": "POKÉPARK",
  "40070": "an event site",
  "40071": "GAME FREAK",
  "40072": "a stadium",
  "40073": "a VGC",
  "40074": "the VGC 2013",
  "40075": "the VGC 2014",
  "40076": "the VGC 2015",
  "40077": "the VGC 2016",
  "40078": "the VGC 2017",
  "40079": "the VGC 2018",
  "60001": "a stranger",
  "60002": "Day Care helpers",
  "60003": "a treasure hunter",
  "60004": "an old hot-springs visitor"
};

var locationName7, location7;
locationName7 = {
  "0": "",
  "2": "Mystery Zone",
  "4": "Faraway Place",
  "6": "Route 1",
  "7": "Hau’oli Outskirts",
  "8": "Route 1",
  "10": "Route 3",
  "12": "Route 2",
  "14": "Kala’e Bay",
  "16": "Melemele Sea",
  "18": "Hau’oli City",
  "19": "Beachfront",
  "20": "Hau’oli City",
  "21": "Shopping District",
  "22": "Hau’oli City",
  "23": "Marina",
  "24": "Iki Town",
  "26": "Mahalo Trail",
  "28": "Mahalo Trail",
  "29": "Plank Bridge",
  "30": "Ruins of Conflict",
  "32": "Ruins of Conflict",
  "34": "Ten Carat Hill",
  "36": "Ten Carat Hill",
  "37": "Farthest Hollow",
  "38": "Hau’oli Cemetery",
  "40": "Melemele Meadow",
  "42": "Seaward Cave",
  "44": "Berry Fields",
  "46": "Verdant Cavern",
  "47": "Trial Site",
  "48": "Verdant Cavern",
  "49": "Totem’s Den",
  "50": "Route 4",
  "52": "Route 5",
  "54": "Route 6",
  "56": "Route 7",
  "58": "Route 8",
  "60": "Route 9",
  "62": "Hano Grand Resort",
  "64": "Hano Beach",
  "66": "Akala Meadow",
  "68": "Paniola Town",
  "70": "Heahea City",
  "72": "Konikoni City",
  "74": "Royal Avenue",
  "76": "Memorial Hill",
  "78": "Paniola Ranch",
  "82": "Wela Volcano Park",
  "84": "Wela Volcano Park",
  "85": "Totem’s Den",
  "86": "Brooklet Hill",
  "88": "Brooklet Hill",
  "89": "Totem’s Den",
  "90": "Lush Jungle",
  "92": "Ruins of Life",
  "94": "Akala Outskirts",
  "100": "Diglett’s Tunnel",
  "102": "Hano Grand Resort",
  "104": "Battle Royal Dome",
  "106": "Route 10",
  "108": "Route 11",
  "110": "Secluded Shore / Ula'ula Beach",
  "112": "Route 13",
  "114": "Tapu Village",
  "116": "Route 15",
  "118": "Route 16",
  "120": "Route 17",
  "122": "Route 12",
  "124": "Haina Desert",
  "126": "Route 14",
  "128": "Ula’ula Meadow",
  "130": "Po Town",
  "132": "Malie City",
  "134": "Malie Garden",
  "136": "Mount Hokulani",
  "138": "Blush Mountain",
  "140": "Ruins of Abundance",
  "142": "Lake of the Sunne",
  "144": "Lake of the Moone",
  "146": "Mount Lanakila",
  "148": "Shady House",
  "150": "Thrifty Megamart",
  "151": "Abandoned Site",
  "152": "Hokulani Observatory",
  "154": "Pokemon League",
  "156": "Poni Meadow",
  "158": "Poni Wilds",
  "160": "Ancient Poni Path",
  "162": "Poni Breaker Coast",
  "164": "Poni Grove",
  "166": "Poni Plains",
  "168": "Poni Coast",
  "170": "Poni Gauntlet",
  "172": "Seafolk Village",
  "174": "Vast Poni Canyon",
  "176": "Altar of the Sunne",
  "178": "Altar of the Moone",
  "180": "Ruins of Hope",
  "182": "Resolution Cave",
  "184": "Exeggutor Island",
  "186": "Battle Tree",
  "188": "Aether Paradise",
  "190": "Ultra Space / Ultra Deep Sea",
  "192": "Malie City",
  "193": "Outer Cape",
  "194": "Melemele",
  "195": "Akala",
  "196": "Ula'ula",
  "197": "Poni",
  "198": "Big Wave Beach",
  "200": "Sandy Cave",
  "202": "Heahea Beach",
  "204": "Poni Beach",
  "206": "Ultra Megalopolis",
  "208": "Megalo Tower",
  "210": "Ultra Plant",
  "212": "Ultra Crater",
  "214": "Ultra Desert",
  "216": "Ultra Forest",
  "218": "Ultra Jungle",
  "220": "Ultra Ruin",
  "222": "Ultra Space Wilds",
  "224": "Team Rocket's Castle",
  "226": "Plains Grotto",
  "228": "Pikachu Valley",
  "230": "Route 1",
  "231": "Trainers' School",
  "232": "Dividing Peak Tunnel",
  "30001": "a Link Trade",
  "30002": "a Link Trade",
  "30003": "the Kanto region",
  "30004": "the Johto region",
  "30005": "the Hoenn region",
  "30006": "the Sinnoh region",
  "30007": "a distant land",
  "30008": "???",
  "30009": "the Unova region",
  "30010": "the Kalos region",
  "30011": "Pokemon Link",
  "30012": "Pokemon GO",
  "30013": "the Kanto region",
  "30014": "the Hoenn region",
  "30015": "the Alola region",
  "30016": "Poke Pelago",
  "30017": "the Johto region",
  "40001": "a lovely place",
  "40002": "a faraway place",
  "40003": "a Pokemon movie",
  "40004": "2016 Pokemon Movie",
  "40005": "2017 Pokemon Movie",
  "40006": "2018 Pokemon Movie",
  "40007": "2019 Pokemon Movie",
  "40008": "2020 Pokemon Movie",
  "40009": "2021 Pokemon Movie",
  "40010": "a Pokemon Center",
  "40011": "the Pokemon animated show",
  "40012": "Pokemon Ctr. MEGA TOKYO",
  "40013": "Pokemon Center Osaka",
  "40014": "Pokemon Center Fukuoka",
  "40015": "Pokemon Center Nagoya",
  "40016": "Pokemon Center Sapporo",
  "40017": "Pokemon Center Yokohama",
  "40018": "Pokemon Center Tohoku",
  "40019": "Pokemon Center TOKYO-BAY",
  "40020": "Pokemon Center Hiroshima",
  "40021": "Pokemon Center Kyoto",
  "40022": "Pokemon Ctr. SKYTREE TOWN",
  "40023": "a Pokemon Store",
  "40024": "a WCS",
  "40025": "WCS 2016",
  "40026": "WCS 2017",
  "40027": "WCS 2018",
  "40028": "WCS 2019",
  "40029": "WCS 2020",
  "40030": "WCS 2021",
  "40031": "Worlds",
  "40032": "2016 Worlds",
  "40033": "2017 Worlds",
  "40034": "2018 Worlds",
  "40035": "2019 Worlds",
  "40036": "2020 Worlds",
  "40037": "2021 Worlds",
  "40038": "a VGE",
  "40039": "VGE 2016",
  "40040": "VGE 2017",
  "40041": "VGE 2018",
  "40042": "VGE 2019",
  "40043": "VGE 2020",
  "40044": "VGE 2021",
  "40045": "a Pokemon event",
  "40046": "a Battle Competition",
  "40047": "a game event",
  "40048": "the Pokemon Daisuki Club",
  "40049": "a Pokemon TV program",
  "40050": "a concert",
  "40051": "an online present",
  "40052": "the PGL",
  "40053": "a 2016 Pokemon event",
  "40054": "a 2017 Pokemon event",
  "40055": "a 2018 Pokemon event",
  "40056": "a 2019 Pokemon event",
  "40057": "a 2020 Pokemon event",
  "40058": "a 2021 Pokemon event",
  "40059": "a Pokemon event",
  "40060": "a 2016 Pokemon event",
  "40061": "a 2017 Pokemon event",
  "40062": "a 2018 Pokemon event",
  "40063": "a 2019 Pokemon event",
  "40064": "a 2020 Pokemon event",
  "40065": "a 2021 Pokemon event",
  "40066": "PokePark",
  "40067": "PokePark 2016",
  "40068": "PokePark 2017",
  "40069": "PokePark 2018",
  "40070": "PokePark 2019",
  "40071": "PokePark 2020",
  "40072": "PokePark 2021",
  "40073": "an event site",
  "40074": "GAME FREAK",
  "40075": "a stadium",
  "40076": "VGC",
  "40077": "the VGC 2016",
  "40078": "the VGC 2017",
  "40079": "the VGC 2018",
  "40080": "the VGC 2019",
  "40081": "the VGC 2020",
  "40082": "the VGC 2021",
  "40083": "a Virtual Console game",
  "40084": "Pokemon GO",
  "40085": "Pokemon Bank",
  "40086": "a Pokemon shop",
  "40087": "a demo version",
  "40088": "the Pokemon Trainer Club",
  "60001": "a stranger",
  "60002": "Nursery helpers",
  "60003": "a treasure hunter",
  "60004": "an old hot-springs visitor"
};

const cardText5 = [
  "Thank you for coming to see the Pokémon Movie! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for coming to see the 2010 Pokémon Movie! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for coming to see the 2011 Pokémon Movie! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for coming to see the 2012 Pokémon Movie! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for coming to see the 2013 Pokémon Movie! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for coming to see the 2014 Pokémon Movie! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for coming to see the 2015 Pokémon Movie! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for coming to see the 2016 Pokémon Movie! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for coming to see the 2017 Pokémon Movie! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for coming to see the 2018 Pokémon Movie! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for coming to see the 2019 Pokémon Movie! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for coming to see the 2020 Pokémon Movie! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for coming to the Pokémon Center! Please pick up your gift from the deliveryman in the game.",
  "Thank you for coming to the Pokémon Center Tokyo! Please pick up your gift from the deliveryman in the game.",
  "Thank you for coming to the Pokémon Center Osaka! Please pick up your gift from the deliveryman in the game.",
  "Thank you for coming to the Pokémon Center Fukuoka! Please pick up your gift from the deliveryman in the game.",
  "Thank you for coming to the Pokémon Center Nagoya! Please pick up your gift from the deliveryman in the game.",
  "Thank you for coming to the Pokémon Center Sapporo! Please pick up your gift from the deliveryman in the game.",
  "Thank you for coming to the Pokémon Center Yokohama! Please pick up your gift from the deliveryman in the game.",
  "Thank you for participating in the Pokémon World Championships! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for participating in the 2010 Pokémon World Championships! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for participating in the 2011 Pokémon World Championships! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for participating in the 2012 Pokémon World Championships! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for participating in the 2013 Pokémon World Championships! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for participating in the 2014 Pokémon World Championships! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for participating in the 2015 Pokémon World Championships! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for participating in the 2016 Pokémon World Championships! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for participating in the 2017 Pokémon World Championships! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for participating in the 2018 Pokémon World Championships! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for participating in the 2019 Pokémon World Championships! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for participating in the 2020 Pokémon World Championships! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for coming to the Pokémon World Championships! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for coming to the 2010 Pokémon World Championships! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for coming to the 2011 Pokémon World Championships! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for coming to the 2012 Pokémon World Championships! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for coming to the 2013 Pokémon World Championships! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for coming to the 2014 Pokémon World Championships! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for coming to the 2015 Pokémon World Championships! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for coming to the 2016 Pokémon World Championships! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for coming to the 2017 Pokémon World Championships! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for coming to the 2018 Pokémon World Championships! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "hank you for coming to the 2019 Pokémon World Championships! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for coming to the 2020 Pokémon World Championships! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for coming to a Pokémon Video Game event! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for coming to a 2010 Pokémon Video Game event! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for coming to a 2011 Pokémon Video Game event! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for coming to a 2012 Pokémon Video Game event! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for coming to a 2013 Pokémon Video Game event! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for coming to a 2014 Pokémon Video Game event! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for coming to a 2015 Pokémon Video Game event! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for coming to a 2016 Pokémon Video Game event! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for coming to a 2017 Pokémon Video Game event! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for coming to a 2018 Pokémon Video Game event! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for coming to a 2019 Pokémon Video Game event! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for coming to a 2020 Pokémon Video Game event! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for participating in a 2010 Pokémon Video Game Championships event! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for participating in a 2011 Pokémon Video Game Championships event! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for participating in a 2012 Pokémon Video Game Championships event! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for participating in a 2013 Pokémon Video Game Championships event! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for participating in a 2014 Pokémon Video Game Championships event! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for participating in a 2015 Pokémon Video Game Championships event! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for participating in a 2016 Pokémon Video Game Championships event! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for participating in a 2017 Pokémon Video Game Championships event! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for participating in a 2018 Pokémon Video Game Championships event! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for participating in a 2019 Pokémon Video Game Championships event! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for participating in a 2020 Pokémon Video Game Championships event! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for coming to the event! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for coming to the Pokémon event! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for playing Pokémon! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for coming to the store! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for participating in the Battle Competition! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for participating in the video-game event! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "This is a gift from the video game event! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "This is a present from the Pokémon Fan Club! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for watching Pokémon Sunday! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "This is a gift from Pokémon Sunday! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for participating in the Challenge Plaza! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "This is a gift from the Challenge Plaza! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for participating in the Battle Challenge! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "This is a gift from the Battle Challenge! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for participating in the Trainers' Court! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "This is a gift from the Trainers' Court! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for participating in the Battle Tour! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "This is a gift from the Battle Tour! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for coming to the Pokémon Concert! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for watching the Pokémon animation! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for playing over Nintendo Wi-Fi Connection! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for receiving this distribution! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for playing the Pokémon Ranger series game! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "The Ranger Union requests that you protect a Pokémon. Please pick it up from the deliveryman in any Pokémon Center.",
  "The Ranger Union requests that you protect an Egg. Please pick it up from the deliveryman in any Pokémon Center.",
  "Thank you for playing in the Pokémon Dream World! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "This is a gift from the Pokémon Dream World! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for playing in the Pokémon DW! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "This is a gift from the Pokémon DW! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for coming to a 2010 Pokémon event! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for coming to a 2011 Pokémon event! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for coming to a 2012 Pokémon event! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for coming to a 2013 Pokémon event! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for coming to a 2014 Pokémon event! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for coming to a 2015 Pokémon event! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for coming to a 2016 Pokémon event! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for coming to a 2017 Pokémon event! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for coming to a 2018 Pokémon event! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for coming to a 2019 Pokémon event! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for coming to a 2020 Pokémon event! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for coming to Pokémon Festa! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for coming to Pokémon Festa 2010! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for coming to Pokémon Festa 2011! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for coming to Pokémon Festa 2012! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for coming to Pokémon Festa 2013! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for coming to Pokémon Festa 2014! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for coming to Pokémon Festa 2015! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for coming to Pokémon Festa 2016! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for coming to Pokémon Festa 2017! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for coming to Pokémon Festa 2018! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for coming to Pokémon Festa 2019! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for coming to Pokémon Festa 2020! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for coming to the PokéPark! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "This is a gift from the PokéPark! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for coming to the PokéPark in 2010! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for coming to the PokéPark in 2011! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for coming to the PokéPark in 2012! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for coming to the PokéPark in 2013! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for coming to the PokéPark in 2014! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for coming to the PokéPark in 2015! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for coming to the PokéPark in 2016! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for coming to the PokéPark in 2017! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for coming to the PokéPark in 2018! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for coming to the PokéPark in 2019! Please pick up your gift from the deliveryman in any Pokémon Center.",
  "Thank you for coming to the PokéPark in 2020! Please pick up your gift from the deliveryman in any Pokémon Center.",
];

const cardText6 = [
  "Thank you for coming to see the Pokémon Movie! Please pick up your gift from the delivery girl in any Pokémon Center.",
  "Thank you for coming to see the 2013 Pokémon Movie! Please pick up your gift from the delivery girl in any Pokémon Center.",
  "Thank you for coming to see the 2014 Pokémon Movie! Please pick up your gift from the delivery girl in any Pokémon Center.",
  "Thank you for coming to see the 2015 Pokémon Movie! Please pick up your gift from the delivery girl in any Pokémon Center.",
  "Thank you for coming to see the 2016 Pokémon Movie! Please pick up your gift from the delivery girl in any Pokémon Center.",
  "Thank you for coming to see the 2017 Pokémon Movie! Please pick up your gift from the delivery girl in any Pokémon Center.",
  "Thank you for coming to see the 2018 Pokémon Movie! Please pick up your gift from the delivery girl in any Pokémon Center.",
  "Thank you for coming to the Pokémon Center! Please pick up your gift from the delivery girl in any Pokémon Center.",
  "Thank you for coming to the Pokémon Center Tokyo! Please pick up your gift from the delivery girl in any Pokémon Center.",
  "Thank you for coming to the Pokémon Center Osaka! Please pick up your gift from the delivery girl in any Pokémon Center.",
  "Thank you for coming to the Pokémon Center Fukuoka! Please pick up your gift from the delivery girl in any Pokémon Center.",
  "Thank you for coming to the Pokémon Center Nagoya! Please pick up your gift from the delivery girl in any Pokémon Center.",
  "Thank you for coming to the Pokémon Center Sapporo! Please pick up your gift from the delivery girl in any Pokémon Center.",
  "Thank you for coming to the Pokémon Center Yokohama! Please pick up your gift from the delivery girl in any Pokémon Center.",
  "Thank you for participating in the Pokémon World Championships! Please pick up your gift from the delivery girl in any Pokémon Center.",
  "Thank you for participating in the 2013 Pokémon World Championships! Please pick up your gift from the delivery girl in any Pokémon Center.",
  "Thank you for participating in the 2014 Pokémon World Championships! Please pick up your gift from the delivery girl in any Pokémon Center.",
  "Thank you for participating in the 2015 Pokémon World Championships! Please pick up your gift from the delivery girl in any Pokémon Center.",
  "Thank you for participating in the 2016 Pokémon World Championships! Please pick up your gift from the delivery girl in any Pokémon Center.",
  "Thank you for participating in the 2017 Pokémon World Championships! Please pick up your gift from the delivery girl in any Pokémon Center.",
  "Thank you for participating in the 2018 Pokémon World Championships! Please pick up your gift from the delivery girl in any Pokémon Center.",
  "Thank you for coming to the Pokémon World Championships! Please pick up your gift from the delivery girl in any Pokémon Center.",
  "Thank you for coming to the 2013 Pokémon World Championships! Please pick up your gift from the delivery girl in any Pokémon Center.",
  "Thank you for coming to the 2014 Pokémon World Championships! Please pick up your gift from the delivery girl in any Pokémon Center.",
  "Thank you for coming to the 2015 Pokémon World Championships! Please pick up your gift from the delivery girl in any Pokémon Center.",
  "Thank you for coming to the 2016 Pokémon World Championships! Please pick up your gift from the delivery girl in any Pokémon Center.",
  "Thank you for coming to the 2017 Pokémon World Championships! Please pick up your gift from the delivery girl in any Pokémon Center.",
  "Thank you for coming to the 2018 Pokémon World Championships! Please pick up your gift from the delivery girl in any Pokémon Center.",
  "Thank you for coming to a Pokémon Video Game event! Please pick up your gift from the delivery girl in any Pokémon Center.",
  "Thank you for coming to a 2013 Pokémon Video Game event! Please pick up your gift from the delivery girl in any Pokémon Center.",
  "Thank you for coming to a 2014 Pokémon Video Game event! Please pick up your gift from the delivery girl in any Pokémon Center.",
  "Thank you for coming to a 2015 Pokémon Video Game event! Please pick up your gift from the delivery girl in any Pokémon Center.",
  "Thank you for coming to a 2016 Pokémon Video Game event! Please pick up your gift from the delivery girl in any Pokémon Center.",
  "Thank you for coming to a 2017 Pokémon Video Game event! Please pick up your gift from the delivery girl in any Pokémon Center.",
  "Thank you for coming to a 2018 Pokémon Video Game event! Please pick up your gift from the delivery girl in any Pokémon Center.",
  "Thank you for participating in the Pokémon Video Game Championships! Please pick up your gift from the delivery girl in any Pokémon Center.",
  "Thank you for participating in a 2013 Pokémon Video Game Championships event! Please pick up your gift from the delivery girl in any Pokémon Center.",
  "Thank you for participating in a 2014 Pokémon Video Game Championships event! Please pick up your gift from the delivery girl in any Pokémon Center.",
  "Thank you for participating in a 2015 Pokémon Video Game Championships event! Please pick up your gift from the delivery girl in any Pokémon Center.",
  "Thank you for participating in a 2016 Pokémon Video Game Championships event! Please pick up your gift from the delivery girl in any Pokémon Center.",
  "Thank you for participating in a 2017 Pokémon Video Game Championships event! Please pick up your gift from the delivery girl in any Pokémon Center.",
  "Thank you for participating in a 2018 Pokémon Video Game Championships event! Please pick up your gift from the delivery girl in any Pokémon Center.",
  "Thank you for coming to the Pokémon event! Please pick up your gift from the delivery girl in any Pokémon Center.",
  "Thank you for playing Pokémon! Please pick up your gift from the delivery girl in any Pokémon Center.",
  "Thank you for coming to the store! Please pick up your gift from the delivery girl in any Pokémon Center.",
  "Thank you for participating in the Battle Competition! Please pick up your gift from the delivery girl in any Pokémon Center.",
  "Thank you for participating in a Pokémon Video Game event! Please pick up your gift from the delivery girl in any Pokémon Center.",
  "This is a gift from the Pokémon Video Game event! Please pick up your gift from the delivery girl in any Pokémon Center.",
  "This is a present from the Pokémon Fan Club! Please pick up your gift from the delivery girl in any Pokémon Center.",
  "Thank you for watching Pokémon programs! Please pick up your gift from the delivery girl in any Pokémon Center.",
  "This is a gift from a Pokémon program! Please pick up your gift from the delivery girl in any Pokémon Center.",
  "Thank you for coming to the Pokémon Concert! Please pick up your gift from the delivery girl in any Pokémon Center.",
  "Thank you for watching the Pokémon animation! Please pick up your gift from the delivery girl in any Pokémon Center.",
  "Thank you for receiving this distribution! Please pick up your gift from the delivery girl in any Pokémon Center.",
  "Please pick up your gift from the delivery girl in any Pokémon Center.",
  "This is a gift from the Pokémon Global Link! Please pick up your gift from the delivery girl in any Pokémon Center.",
  "Thank you for visiting the Pokémon Global Link! Please pick up your gift from the delivery girl in any Pokémon Center.",
  "This is a gift from the Pokémon Global Link! Please pick up your gift from the delivery girl in any Pokémon Center.",
  "Thank you for coming to the Pokémon event! Please pick up your gift from the delivery girl in any Pokémon Center.",
  "Thank you for coming to a 2013 Pokémon event! Please pick up your gift from the delivery girl in any Pokémon Center.",
  "Thank you for coming to a 2014 Pokémon event! Please pick up your gift from the delivery girl in any Pokémon Center.",
  "Thank you for coming to a 2015 Pokémon event! Please pick up your gift from the delivery girl in any Pokémon Center.",
  "Thank you for coming to a 2016 Pokémon event! Please pick up your gift from the delivery girl in any Pokémon Center.",
  "Thank you for coming to a 2017 Pokémon event! Please pick up your gift from the delivery girl in any Pokémon Center.",
  "Thank you for coming to a 2018 Pokémon event! Please pick up your gift from the delivery girl in any Pokémon Center.",
  "Thank you for coming to Pokémon Festa! Please pick up your gift from the delivery girl in any Pokémon Center.",
  "Thank you for coming to Pokémon Festa 2013! Please pick up your gift from the delivery girl in any Pokémon Center.",
  "Thank you for coming to Pokémon Festa 2014! Please pick up your gift from the delivery girl in any Pokémon Center.",
  "Thank you for coming to Pokémon Festa 2015! Please pick up your gift from the delivery girl in any Pokémon Center.",
  "Thank you for coming to Pokémon Festa 2016! Please pick up your gift from the delivery girl in any Pokémon Center.",
  "Thank you for coming to Pokémon Festa 2017! Please pick up your gift from the delivery girl in any Pokémon Center.",
  "Thank you for coming to Pokémon Festa 2018! Please pick up your gift from the delivery girl in any Pokémon Center.",
  "Thank you for coming to the PokéPark! Please pick up your gift from the delivery girl in any Pokémon Center.",
  "This is a gift from the PokéPark! Please pick up your gift from the delivery girl in any Pokémon Center.",
  "Thank you for coming to the PokéPark in 2013! Please pick up your gift from the delivery girl in any Pokémon Center.",
  "Thank you for coming to the PokéPark in 2014! Please pick up your gift from the delivery girl in any Pokémon Center.",
  "Thank you for coming to the PokéPark in 2015! Please pick up your gift from the delivery girl in any Pokémon Center.",
  "Thank you for coming to the PokéPark in 2016! Please pick up your gift from the delivery girl in any Pokémon Center.",
  "Thank you for coming to the PokéPark in 2017! Please pick up your gift from the delivery girl in any Pokémon Center.",
  "Thank you for coming to the PokéPark in 2018! Please pick up your gift from the delivery girl in any Pokémon Center.",
  "Thank you for coming to the event! Please pick up your gift from the delivery girl in any Pokémon Center.",
  "Thank you for coming to the Pokémon Center Tohoku! Please pick up your gift from the delivery girl in any Pokémon Center.",
  "This is a gift from GAME FREAK! Please pick up your gift from the delivery girl in any Pokémon Center.",
  "Thank you for coming to the stadium! Please pick up your gift from the delivery girl in any Pokémon Center.",
  "Thank you for coming to the Pokémon Center Tokyo Bay! Please pick up your gift from the delivery girl in any Pokémon Center.",
  "Thank you for coming to the Pokémon Store! Please pick up your gift from the delivery girl in any Pokémon Center.",
];

const cardText7 = [
  "Please pick up your gift from the deliveryman in any Pokemon Center.",
  "Thanks for coming to see the Pokemon Movie! Please pick up your gift from the deliveryman in any Pokemon Center.",
  "Thank you for coming to see the 2016 Pokemon Movie! Please pick up your gift from the deliveryman in any Pokemon Center.",
  "Thank you for coming to see the 2017 Pokemon Movie! Please pick up your gift from the deliveryman in any Pokemon Center.",
  "Thank you for coming to see the 2018 Pokemon Movie! Please pick up your gift from the deliveryman in any Pokemon Center.",
  "Thank you for coming to see the 2019 Pokemon Movie! Please pick up your gift from the deliveryman in any Pokemon Center.",
  "Thank you for coming to see the 2020 Pokemon Movie! Please pick up your gift from the deliveryman in any Pokemon Center.",
  "Thank you for coming to see the 2021 Pokemon Movie! Please pick up your gift from the deliveryman in any Pokemon Center.",
  "Thank you for coming to the Pokemon Center! Please pick up your gift from the deliveryman in the game.",
  "Thank you for coming to the Pokemon Center MEGA TOKYO! Please pick up your gift from the deliveryman in the game.",
  "Thank you for coming to the Pokemon Center Osaka! Please pick up your gift from the deliveryman in the game.",
  "Thank you for coming to the Pokemon Center Fukuoka! Please pick up your gift from the deliveryman in the game.",
  "Thank you for coming to the Pokemon Center Nagoya! Please pick up your gift from the deliveryman in the game.",
  "Thank you for coming to the Pokemon Center Sapporo! Please pick up your gift from the deliveryman in the game.",
  "Thank you for coming to the Pokemon Center Yokohama! Please pick up your gift from the deliveryman in the game.",
  "Thank you for participating in the Pokemon World Championships! Please pick up your gift from the deliveryman in any Pokemon Center.",
  "Thanks for participating in the 2016 Pokemon World Championships! Please pick up your gift from the deliveryman in any Pokemon Center.",
  "Thanks for participating in the 2017 Pokemon World Championships! Please pick up your gift from the deliveryman in any Pokemon Center.",
  "Thanks for participating in the 2018 Pokemon World Championships! Please pick up your gift from the deliveryman in any Pokemon Center.",
  "Thanks for participating in the 2019 Pokemon World Championships! Please pick up your gift from the deliveryman in any Pokemon Center.",
  "Thanks for participating in the 2020 Pokemon World Championships! Please pick up your gift from the deliveryman in any Pokemon Center.",
  "Thanks for participating in the 2021 Pokemon World Championships! Please pick up your gift from the deliveryman in any Pokemon Center.",
  "Thank you for coming to the Pokemon World Championships! Please pick up your gift from the deliveryman in any Pokemon Center.",
  "Thank you for coming to the 2016 Pokemon World Championships! Please pick up your gift from the deliveryman in any Pokemon Center.",
  "Thank you for coming to the 2017 Pokemon World Championships! Please pick up your gift from the deliveryman in any Pokemon Center.",
  "Thank you for coming to the 2018 Pokemon World Championships! Please pick up your gift from the deliveryman in any Pokemon Center.",
  "Thank you for coming to the 2019 Pokemon World Championships! Please pick up your gift from the deliveryman in any Pokemon Center.",
  "Thank you for coming to the 2020 Pokemon World Championships! Please pick up your gift from the deliveryman in any Pokemon Center.",
  "Thank you for coming to the 2021 Pokemon World Championships! Please pick up your gift from the deliveryman in any Pokemon Center.",
  "Thank you for coming to a Pokemon Video Game event! Please pick up your gift from the delivery man in any Pokemon Center.",
  "Thank you for coming to a 2016 Pokemon Video Game event! Please pick up your gift from the deliveryman in any Pokemon Center.",
  "Thank you for coming to a 2017 Pokemon Video Game event! Please pick up your gift from the deliveryman in any Pokemon Center.",
  "Thank you for coming to a 2018 Pokemon Video Game event! Please pick up your gift from the deliveryman in any Pokemon Center.",
  "Thank you for coming to a 2019 Pokemon Video Game event! Please pick up your gift from the deliveryman in any Pokemon Center.",
  "Thank you for coming to a 2020 Pokemon Video Game event! Please pick up your gift from the deliveryman in any Pokemon Center.",
  "Thank you for coming to a 2021 Pokemon Video Game event! Please pick up your gift from the deliveryman in any Pokemon Center.",
  "Thanks for participating in the Pokemon Video Game Championships! Please pick up your gift from the deliveryman in any Pokemon Center.",
  "Thank you for participating in a 2016 Pokemon Video Game Championships event! Please pick up your gift from the deliveryman in any Pokemon Center.",
  "Thank you for participating in a 2017 Pokemon Video Game Championships event! Please pick up your gift from the deliveryman in any Pokemon Center.",
  "Thank you for participating in a 2018 Pokemon Video Game Championships event! Please pick up your gift from the deliveryman in any Pokemon Center.",
  "Thank you for participating in a 2019 Pokemon Video Game Championships event! Please pick up your gift from the deliveryman in any Pokemon Center.",
  "Thank you for participating in a 2020 Pokemon Video Game Championships event! Please pick up your gift from the deliveryman in any Pokemon Center.",
  "Thank you for participating in a 2021 Pokemon Video Game Championships event! Please pick up your gift from the deliveryman in any Pokemon Center.",
  "Thank you for coming to the Pokemon event! Please pick up your gift from the deliveryman in any Pokemon Center.",
  "Thank you for playing Pokemon! Please pick up your gift from the deliveryman in any Pokemon Center.",
  "Thank you for coming to the store! Please pick up your gift from the deliveryman in any Pokemon Center.",
  "Thank you for participating in the Battle Competition! Please pick up your gift from the deliveryman in any Pokemon Center.",
  "Thank you for participating in a Pokemon Video Game event! Please pick up your gift from the deliveryman in any Pokemon Center.",
  "This is a gift from the Pokemon Video Game event! Please pick up your gift from the deliveryman in any Pokemon Center.",
  "This is a present from the Pokemon Daisuki Club! Please pick up your gift from the deliveryman in any Pokemon Center.",
  "Thank you for watching Pokemon programs! Please pick up your gift from the deliveryman in any Pokemon Center.",
  "This is a gift from a Pokemon program! Please pick up your gift from the deliveryman in any Pokemon Center.",
  "Thank you for coming to the Pokemon Concert! Please pick up your gift from the deliveryman in any Pokemon Center.",
  "Thank you for watching the Pokemon animation! Please pick up your gift from the deliveryman in any Pokemon Center.",
  "Thank you for receiving this distribution! Please pick up your gift from the deliveryman in any Pokemon Center.",
  "Please pick up your gift from the deliveryman in any Pokemon Center.",
  "This is a gift from the Pokemon Global Link! Please pick up your gift from the deliveryman in any Pokemon Center.",
  "Thank you for visiting the Pokemon Global Link! Please pick up your gift from the deliveryman in any Pokemon Center.",
  "This is a gift from the Pokemon Global Link! Please pick up your gift from the deliveryman in any Pokemon Center.",
  "Thank you for coming to the Pokemon event! Please pick up your gift from the deliveryman in any Pokemon Center.",
  "Thanks for coming to a 2016 Pokemon event! Please pick up your gift from the deliveryman in any Pokemon Center.",
  "Thanks for coming to a 2017 Pokemon event! Please pick up your gift from the deliveryman in any Pokemon Center.",
  "Thanks for coming to a 2018 Pokemon event! Please pick up your gift from the deliveryman in any Pokemon Center.",
  "Thanks for coming to a 2019 Pokemon event! Please pick up your gift from the deliveryman in any Pokemon Center.",
  "Thanks for coming to a 2020 Pokemon event! Please pick up your gift from the deliveryman in any Pokemon Center.",
  "Thanks for coming to a 2021 Pokemon event! Please pick up your gift from the deliveryman in any Pokemon Center.",
  "Thank you for coming to a Pokemon event! Please pick up your gift from the deliveryman in any Pokemon Center.",
  "Thanks for coming to a 2016 Pokemon event! Please pick up your gift from the deliveryman in any Pokemon Center.",
  "Thanks for coming to a 2017 Pokemon event! Please pick up your gift from the deliveryman in any Pokemon Center.",
  "Thanks for coming to a 2018 Pokemon event! Please pick up your gift from the deliveryman in any Pokemon Center.",
  "Thanks for coming to a 2019 Pokemon event! Please pick up your gift from the deliveryman in any Pokemon Center.",
  "Thanks for coming to a 2020 Pokemon event! Please pick up your gift from the deliveryman in any Pokemon Center.",
  "Thanks for coming to a 2021 Pokemon event! Please pick up your gift from the deliveryman in any Pokemon Center.",
  "Thank you for coming to the PokePark! Please pick up your gift from the deliveryman in any Pokemon Center.",
  "This is a gift from the PokePark! Please pick up your gift from the deliveryman in any Pokemon Center.",
  "Thank you for coming to the PokePark in 2016! Please pick up your gift from the deliveryman in any Pokemon Center.",
  "Thank you for coming to the PokePark in 2017! Please pick up your gift from the deliveryman in any Pokemon Center.",
  "Thank you for coming to the PokePark in 2018! Please pick up your gift from the deliveryman in any Pokemon Center.",
  "Thank you for coming to the PokePark in 2019! Please pick up your gift from the deliveryman in any Pokemon Center.",
  "Thank you for coming to the PokePark in 2020! Please pick up your gift from the deliveryman in any Pokemon Center.",
  "Thank you for coming to the PokePark in 2021! Please pick up your gift from the deliveryman in any Pokemon Center.",
  "Thank you for coming to the event! Please pick up your gift from the deliveryman in any Pokemon Center.",
  "Thank you for coming to the Pokemon Center Tohoku! Please pick up your gift from the deliveryman in the game.",
  "This is a gift from GAME FREAK! Please pick up your gift from the deliveryman in any Pokemon Center.",
  "Thank you for coming to the stadium! Please pick up your gift from the deliveryman in any Pokemon Center.",
  "Thank you for coming to the Pokemon Center TOKYO-BAY! Please pick up your gift from the deliveryman in the game.",
  "Thank you for coming to the Pokemon Store! Please pick up your gift from the deliveryman in the game.",
  "Thank you for playing the Virtual Console! Please pick up your gift from the deliveryman in any Pokemon Center.",
  "Thank you for playing Pokemon GO! Please pick up your gift from the deliveryman in any Pokemon Center.",
  "Thank you for playing Pokemon Bank! Please pick up your gift from the deliveryman in any Pokemon Center.",
  "Thank you for coming to the Pokemon Shop! Please pick up your gift from the deliveryman in the game.",
  "Thank you for playing the demo version! Please pick up your gift from the deliveryman in any Pokemon Center.",
  "Thank you for coming to the Pokemon Center Hiroshima! Please pick up your gift from the deliveryman in the game.",
  "Thank you for coming to the Pokemon Center Kyoto! Please pick up your gift from the deliveryman in the game.",
  "Thank you for coming to the Pokemon Center SKYTREE TOWN. Please pick up your gift from the deliveryman in the game.",
  "This is a present from the Pokemon Trainer Club! Please pick up your gift from the deliveryman in any Pokemon Center.",
];

var ribbonName5A, ribbon;
ribbonName5A = {
  "0": "",
  "1": "Country Ribbon",
  "2": "National Ribbon",
  "4": "Earth Ribbon",
  "8": "World Ribbon",
  "16": "Classic Ribbon",
  "32": "Premier Ribbon",
  "64": "Event Ribbon",
  "128": "Birthday Ribbon",
};
var ribbonName5B, ribbon;
ribbonName5B = {
  "0": "",
  "1": "Special Ribbon",
  "2": "Souvenir Ribbon",
  "4": "Wishing Ribbon",
  "8": "Battle Champ Ribbon",
  "16": "Regional Champ Ribbon",
  "32": "National Champ Ribbon",
  "64": "World Champ Ribbon",
};

var ribbonName67A, ribbon;
ribbonName67A = {
  "0": "",
  "1": "Battle Champ Ribbon",
  "2": "Regional Champ Ribbon",
  "4": "National Champ Ribbon",
  "8": "Country Ribbon",
  "16": "National Ribbon",
  "32": "Earth Ribbon",
  "64": "World Ribbon",
  "128": "Event Ribbon",
};
var ribbonName67B, ribbon;
ribbonName67B = {
  "0": "",
  "1": "World Champ Ribbon",
  "2": "Birthday Ribbon",
  "4": "Special Ribbon",
  "8": "Souvenir Ribbon",
  "16": "Wishing Ribbon",
  "32": "Classic Ribbon",
  "64": "Premier Ribbon",
};